export const FETCH_MIXTURE_BY_BREW_ID_REQUEST =
    "FETCH_MIXTURE_BY_BREW_ID_REQUEST";
export const FETCH_MIXTURE_BY_BREW_ID_SUCCESS =
    "FETCH_MIXTURE_BY_BREW_ID_SUCCESS";
export const FETCH_MIXTURE_BY_BREW_ID_FAILURE =
    "FETCH_MIXTURE_BY_BREW_ID_FAILURE";
export const SET_BREW_MIXTURE_DETAILS = "SET_BREW_MIXTURE_DETAILS";
export const RESET_BREW_MIXTURE_DETAILS = "RESET_BREW_MIXTURE_DETAILS";
export const ADD_BREW_MIXTURES_REQUEST = "ADD_BREW_MIXTURES_REQUEST";
export const ADD_BREW_MIXTURE_SUCCESS = "ADD_BREW_MIXTURE_SUCCESS";
export const ADD_BREW_MIXTURE_FAILURE = "ADD_BREW_MIXTURE_FAILURE";
export const EDIT_BREW_MIXTURES_REQUEST = "EDIT_BREW_MIXTURES_REQUEST";
export const EDIT_BREW_MIXTURE_SUCCESS = "EDIT_BREW_MIXTURE_SUCCESS";
export const EDIT_BREW_MIXTURE_FAILURE = "EDIT_BREW_MIXTURE_FAILURE";
export const DELETE_BREW_MIXTURES_REQUEST = "DELETE_BREW_MIXTURES_REQUEST";
export const DELETE_BREW_MIXTURE_SUCCESS = "DELETE_BREW_MIXTURE_SUCCESS";
export const DELETE_BREW_MIXTURE_FAILURE = "DELETE_BREW_MIXTURE_FAILURE";
