export const FETCH_BATCH_TASK_REQUEST = "FETCH_BATCH_TASK_REQUEST";
export const FETCH_BATCH_TASK_SUCCESS = "FETCH_BATCH_TASK_SUCCESS";
export const FETCH_BATCH_TASK_FAILURE = "FETCH_BATCH_TASK_FAILURE";
export const SET_BATCH_TASK_DETAILS = "SET_BATCH_TASK_DETAILS";
export const SET_BATCH_TASK_PAGE_INDEX = "SET_BATCH_TASK_PAGE_INDEX";
export const SET_BATCH_TASK_PAGE_SIZE = "SET_BATCH_TASK_PAGE_SIZE";