export const FETCH_MIXTURE_BY_BREW_ID_REQUEST =
    "FETCH_MIXTURE_BY_BREW_ID_REQUEST";
export const FETCH_MIXTURE_BY_BREW_ID_SUCCESS =
    "FETCH_MIXTURE_BY_BREW_ID_SUCCESS";
export const FETCH_MIXTURE_BY_BREW_ID_FAILURE =
    "FETCH_MIXTURE_BY_BREW_ID_FAILURE";
export const SET_BREW_MIXTURE_DETAILS = "SET_BREW_MIXTURE_DETAILS";
export const RESET_BREW_MIXTURE_DETAILS = "RESET_BREW_MIXTURE_DETAILS";
export const ADD_BREW_MIXTURES_REQUEST = "ADD_BREW_MIXTURES_REQUEST";
export const ADD_BREW_MIXTURE_SUCCESS = "ADD_BREW_MIXTURE_SUCCESS";
export const ADD_BREW_MIXTURE_FAILURE = "ADD_BREW_MIXTURE_FAILURE";
export const EDIT_BREW_MIXTURES_REQUEST = "EDIT_BREW_MIXTURES_REQUEST";
export const EDIT_BREW_MIXTURE_SUCCESS = "EDIT_BREW_MIXTURE_SUCCESS";
export const EDIT_BREW_MIXTURE_FAILURE = "EDIT_BREW_MIXTURE_FAILURE";
export const DELETE_BREW_MIXTURES_REQUEST = "DELETE_BREW_MIXTURES_REQUEST";
export const DELETE_BREW_MIXTURE_SUCCESS = "DELETE_BREW_MIXTURE_SUCCESS";
export const DELETE_BREW_MIXTURE_FAILURE = "DELETE_BREW_MIXTURE_FAILURE";

export const SET_MASH_MIXTURE_DETAILS = "SET_MASH_MIXTURE_DETAILS";
export const RESET_MASH_MIXTURE_DETAILS = "RESET_MASH_MIXTURE_DETAILS";

export const SET_KETTLE_MIXTURE_DETAILS = "SET_KETTLE_MIXTURE_DETAILS";
export const RESET_KETTLE_MIXTURE_DETAILS = "RESET_KETTLE_MIXTURE_DETAILS";

export const SET_WHIRLPOOL_MIXTURE_DETAILS = "SET_WHIRLPOOL_MIXTURE_DETAILS";
export const RESET_WHIRLPOOL_MIXTURE_DETAILS =
    "RESET_WHIRLPOOL_MIXTURE_DETAILS";

export const SET_TRANSFER_MIXTURE_DETAILS = "SET_TRANSFER_MIXTURE_DETAILS";
export const RESET_TRANSFER_MIXTURE_DETAILS = "RESET_TRANSFER_MIXTURE_DETAILS";

export const FETCH_FERMENT_MIXTURE_BY_ID_REQUEST =
    "FETCH_FERMENT_MIXTURE_BY_ID_REQUEST";
export const FETCH_FERMENT_MIXTURE_BY_ID_FAILURE =
    "FETCH_FERMENT_MIXTURE_BY_ID_FAILURE";
export const ADD_FERMENT_MIXTURE_REQUEST = "ADD_FERMENT_MIXTURE_REQUEST";
export const ADD_FERMENT_MIXTURE_SUCCESS = "ADD_FERMENT_MIXTURE_SUCCESS";
export const ADD_FERMENT_MIXTURE_FAILURE = "ADD_FERMENT_MIXTURE_FAILURE";
export const EDIT_FERMENT_MIXTURE_REQUEST = "EDIT_FERMENT_MIXTURE_REQUEST";
export const EDIT_FERMENT_MIXTURE_SUCCESS = "EDIT_FERMENT_MIXTURE_SUCCESS";
export const EDIT_FERMENT_MIXTURE_FAILURE = "EDIT_FERMENT_MIXTURE_FAILURE";
export const DELETE_FERMENT_MIXTURE_REQUEST = "DELETE_FERMENT_MIXTURE_REQUEST";
export const DELETE_FERMENT_MIXTURE_SUCCESS = "DELETE_FERMENT_MIXTURE_SUCCESS";
export const DELETE_FERMENT_MIXTURE_FAILURE = "DELETE_FERMENT_MIXTURE_FAILURE";
export const SET_FERMENT_MIXTURE_DETAILS = "SET_FERMENT_MIXTURE_DETAILS";
export const RESET_FERMENT_MIXTURE_DETAILS = "RESET_FERMENT_MIXTURE_DETAILS";
export const SET_FERMENT_MIXTURE_INVALID_NAME =
    "SET_FERMENT_MIXTURE_INVALID_NAME";
export const SET_FERMENT_MIXTURE_INVALID_CATEGORY =
    "SET_FERMENT_MIXTURE_INVALID_CATEGORY";
