export const FETCH_MIXTURE_BY_BREW_ID_REQUEST =
    "FETCH_MIXTURE_BY_BREW_ID_REQUEST";
export const FETCH_MIXTURE_BY_BREW_ID_SUCCESS =
    "FETCH_MIXTURE_BY_BREW_ID_SUCCESS";
export const FETCH_MIXTURE_BY_BREW_ID_FAILURE =
    "FETCH_MIXTURE_BY_BREW_ID_FAILURE";
export const SET_MIXTURES = "SET_MIXTURES";
export const RESET_MIXTURES = "RESET_MIXTURES";
export const SET_BREW_MIXTURE_DETAILS = "SET_BREW_MIXTURE_DETAILS";

export const FETCH_MASH_MIXTURE_BY_ID_REQUEST =
    "FETCH_MASH_MIXTURE_BY_ID_REQUEST";
export const ADD_MASH_MIXTURE_REQUEST = "ADD_MASH_MIXTURE_REQUEST";
export const ADD_MASH_MIXTURE_SUCCESS = "ADD_MASH_MIXTURE_SUCCESS";
export const ADD_MASH_MIXTURE_FAILURE = "ADD_MASH_MIXTURE_FAILURE";
export const EDIT_MASH_MIXTURE_REQUEST = "EDIT_MASH_MIXTURE_REQUEST";
export const EDIT_MASH_MIXTURE_SUCCESS = "EDIT_MASH_MIXTURE_SUCCESS";
export const EDIT_MASH_MIXTURE_FAILURE = "EDIT_MASH_MIXTURE_FAILURE";
export const DELETE_MASH_MIXTURE_REQUEST = "DELETE_MASH_MIXTURE_REQUEST";
export const DELETE_MASH_MIXTURE_SUCCESS = "DELETE_MASH_MIXTURE_SUCCESS";
export const DELETE_MASH_MIXTURE_FAILURE = "DELETE_MASH_MIXTURE_FAILURE";
export const SET_MASH_MIXTURE_DETAILS = "SET_MASH_MIXTURE_DETAILS";
export const RESET_MASH_MIXTURE_DETAILS = "RESET_MASH_MIXTURE_DETAILS";
export const SET_MASH_MIXTURE_INVALID_NAME = "SET_MASH_MIXTURE_INVALID_NAME";
export const SET_MASH_MIXTURE_INVALID_CATEGORY =
    "SET_MASH_MIXTURE_INVALID_CATEGORY";

export const FETCH_KETTLE_MIXTURE_BY_ID_REQUEST =
    "FETCH_KETTLE_MIXTURE_BY_ID_REQUEST";
export const ADD_KETTLE_MIXTURE_REQUEST = "ADD_KETTLE_MIXTURE_REQUEST";
export const ADD_KETTLE_MIXTURE_SUCCESS = "ADD_KETTLE_MIXTURE_SUCCESS";
export const ADD_KETTLE_MIXTURE_FAILURE = "ADD_KETTLE_MIXTURE_FAILURE";
export const EDIT_KETTLE_MIXTURE_REQUEST = "EDIT_KETTLE_MIXTURE_REQUEST";
export const EDIT_KETTLE_MIXTURE_SUCCESS = "EDIT_KETTLE_MIXTURE_SUCCESS";
export const EDIT_KETTLE_MIXTURE_FAILURE = "EDIT_KETTLE_MIXTURE_FAILURE";
export const DELETE_KETTLE_MIXTURE_REQUEST = "DELETE_KETTLE_MIXTURE_REQUEST";
export const DELETE_KETTLE_MIXTURE_SUCCESS = "DELETE_KETTLE_MIXTURE_SUCCESS";
export const DELETE_KETTLE_MIXTURE_FAILURE = "DELETE_KETTLE_MIXTURE_FAILURE";
export const SET_KETTLE_MIXTURE_DETAILS = "SET_KETTLE_MIXTURE_DETAILS";
export const RESET_KETTLE_MIXTURE_DETAILS = "RESET_KETTLE_MIXTURE_DETAILS";
export const SET_KETTLE_MIXTURE_INVALID_NAME =
    "SET_KETTLE_MIXTURE_INVALID_NAME";
export const SET_KETTLE_MIXTURE_INVALID_CATEGORY =
    "SET_KETTLE_MIXTURE_INVALID_CATEGORY";

export const FETCH_WHIRLPOOL_MIXTURE_BY_ID_REQUEST =
    "FETCH_WHIRLPOOL_MIXTURE_BY_ID_REQUEST";
export const ADD_WHIRLPOOL_MIXTURE_REQUEST = "ADD_WHIRLPOOL_MIXTURE_REQUEST";
export const ADD_WHIRLPOOL_MIXTURE_SUCCESS = "ADD_WHIRLPOOL_MIXTURE_SUCCESS";
export const ADD_WHIRLPOOL_MIXTURE_FAILURE = "ADD_WHIRLPOOL_MIXTURE_FAILURE";
export const EDIT_WHIRLPOOL_MIXTURE_REQUEST = "EDIT_WHIRLPOOL_MIXTURE_REQUEST";
export const EDIT_WHIRLPOOL_MIXTURE_SUCCESS = "EDIT_WHIRLPOOL_MIXTURE_SUCCESS";
export const EDIT_WHIRLPOOL_MIXTURE_FAILURE = "EDIT_WHIRLPOOL_MIXTURE_FAILURE";
export const DELETE_WHIRLPOOL_MIXTURE_REQUEST =
    "DELETE_WHIRLPOOL_MIXTURE_REQUEST";
export const DELETE_WHIRLPOOL_MIXTURE_SUCCESS =
    "DELETE_WHIRLPOOL_MIXTURE_SUCCESS";
export const DELETE_WHIRLPOOL_MIXTURE_FAILURE =
    "DELETE_WHIRLPOOL_MIXTURE_FAILURE";
export const SET_WHIRLPOOL_MIXTURE_DETAILS = "SET_WHIRLPOOL_MIXTURE_DETAILS";
export const RESET_WHIRLPOOL_MIXTURE_DETAILS =
    "RESET_WHIRLPOOL_MIXTURE_DETAILS";
export const SET_WHIRLPOOL_MIXTURE_INVALID_NAME =
    "SET_WHIRLPOOL_MIXTURE_INVALID_NAME";
export const SET_WHIRLPOOL_MIXTURE_INVALID_CATEGORY =
    "SET_WHIRLPOOL_MIXTURE_INVALID_CATEGORY";

export const FETCH_TRANSFER_MIXTURE_BY_ID_REQUEST =
    "FETCH_TRANSFER_MIXTURE_BY_ID_REQUEST";
export const ADD_TRANSFER_MIXTURE_REQUEST = "ADD_TRANSFER_MIXTURE_REQUEST";
export const ADD_TRANSFER_MIXTURE_SUCCESS = "ADD_TRANSFER_MIXTURE_SUCCESS";
export const ADD_TRANSFER_MIXTURE_FAILURE = "ADD_TRANSFER_MIXTURE_FAILURE";
export const EDIT_TRANSFER_MIXTURE_REQUEST = "EDIT_TRANSFER_MIXTURE_REQUEST";
export const EDIT_TRANSFER_MIXTURE_SUCCESS = "EDIT_TRANSFER_MIXTURE_SUCCESS";
export const EDIT_TRANSFER_MIXTURE_FAILURE = "EDIT_TRANSFER_MIXTURE_FAILURE";
export const DELETE_TRANSFER_MIXTURE_REQUEST =
    "DELETE_TRANSFER_MIXTURE_REQUEST";
export const DELETE_TRANSFER_MIXTURE_SUCCESS =
    "DELETE_TRANSFER_MIXTURE_SUCCESS";
export const DELETE_TRANSFER_MIXTURE_FAILURE =
    "DELETE_TRANSFER_MIXTURE_FAILURE";
export const SET_TRANSFER_MIXTURE_DETAILS = "SET_TRANSFER_MIXTURE_DETAILS";
export const RESET_TRANSFER_MIXTURE_DETAILS = "RESET_TRANSFER_MIXTURE_DETAILS";
export const SET_TRANSFER_MIXTURE_INVALID_NAME =
    "SET_TRANSFER_MIXTURE_INVALID_NAME";
export const SET_TRANSFER_MIXTURE_INVALID_CATEGORY =
    "SET_TRANSFER_MIXTURE_INVALID_CATEGORY";

export const FETCH_FERMENT_MIXTURE_BY_ID_REQUEST =
    "FETCH_FERMENT_MIXTURE_BY_ID_REQUEST";
export const FETCH_FERMENT_MIXTURE_BY_ID_FAILURE =
    "FETCH_FERMENT_MIXTURE_BY_ID_FAILURE";
export const ADD_FERMENT_MIXTURE_REQUEST = "ADD_FERMENT_MIXTURE_REQUEST";
export const ADD_FERMENT_MIXTURE_SUCCESS = "ADD_FERMENT_MIXTURE_SUCCESS";
export const ADD_FERMENT_MIXTURE_FAILURE = "ADD_FERMENT_MIXTURE_FAILURE";
export const EDIT_FERMENT_MIXTURE_REQUEST = "EDIT_FERMENT_MIXTURE_REQUEST";
export const EDIT_FERMENT_MIXTURE_SUCCESS = "EDIT_FERMENT_MIXTURE_SUCCESS";
export const EDIT_FERMENT_MIXTURE_FAILURE = "EDIT_FERMENT_MIXTURE_FAILURE";
export const DELETE_FERMENT_MIXTURE_REQUEST = "DELETE_FERMENT_MIXTURE_REQUEST";
export const DELETE_FERMENT_MIXTURE_SUCCESS = "DELETE_FERMENT_MIXTURE_SUCCESS";
export const DELETE_FERMENT_MIXTURE_FAILURE = "DELETE_FERMENT_MIXTURE_FAILURE";
export const SET_FERMENT_MIXTURE_DETAILS = "SET_FERMENT_MIXTURE_DETAILS";
export const RESET_FERMENT_MIXTURE_DETAILS = "RESET_FERMENT_MIXTURE_DETAILS";
export const SET_FERMENT_MIXTURE_INVALID_NAME =
    "SET_FERMENT_MIXTURE_INVALID_NAME";
export const SET_FERMENT_MIXTURE_INVALID_CATEGORY =
    "SET_FERMENT_MIXTURE_INVALID_CATEGORY";

export const FETCH_CONDITION_MIXTURE_BY_ID_REQUEST =
    "FETCH_CONDITION_MIXTURE_BY_ID_REQUEST";
export const ADD_CONDITION_MIXTURE_REQUEST = "ADD_CONDITION_MIXTURE_REQUEST";
export const ADD_CONDITION_MIXTURE_SUCCESS = "ADD_CONDITION_MIXTURE_SUCCESS";
export const ADD_CONDITION_MIXTURE_FAILURE = "ADD_CONDITION_MIXTURE_FAILURE";
export const EDIT_CONDITION_MIXTURE_REQUEST = "EDIT_CONDITION_MIXTURE_REQUEST";
export const EDIT_CONDITION_MIXTURE_SUCCESS = "EDIT_CONDITION_MIXTURE_SUCCESS";
export const EDIT_CONDITION_MIXTURE_FAILURE = "EDIT_CONDITION_MIXTURE_FAILURE";
export const DELETE_CONDITION_MIXTURE_REQUEST =
    "DELETE_CONDITION_MIXTURE_REQUEST";
export const DELETE_CONDITION_MIXTURE_SUCCESS =
    "DELETE_CONDITION_MIXTURE_SUCCESS";
export const DELETE_CONDITION_MIXTURE_FAILURE =
    "DELETE_CONDITION_MIXTURE_FAILURE";
export const SET_CONDITION_MIXTURE_DETAILS = "SET_CONDITION_MIXTURE_DETAILS";
export const RESET_CONDITION_MIXTURE_DETAILS =
    "RESET_CONDITION_MIXTURE_DETAILS";
export const SET_CONDITION_MIXTURE_INVALID_NAME =
    "SET_CONDITION_MIXTURE_INVALID_NAME";
export const SET_CONDITION_MIXTURE_INVALID_CATEGORY =
    "SET_CONDITION_MIXTURE_INVALID_CATEGORY";
