export const FETCH_BREW_FINISHED_GOODS_SUCCESS =
    "FETCH_BREW_FINISHED_GOODS_SUCCESS";
export const FETCH_BREW_FINISHED_GOODS_FAILURE =
    "FETCH_BREW_FINISHED_GOODS_FAILURE";
export const FETCH_BREW_FINISHED_GOODS_REQUEST =
    "FETCH_BREW_FINISHED_GOODS_REQUEST";
export const EDIT_BREW_FINISHED_GOODS_REQUEST =
    "EDIT_BREW_FINISHED_GOODS_REQUEST";
export const EDIT_BREW_FINISHED_GOODS_SUCCESS =
    "EDIT_BREW_FINISHED_GOODS_SUCCESS";
export const EDIT_BREW_FINISHED_GOODS_FAILURE =
    "EDIT_BREW_FINISHED_GOODS_FAILURE";
export const DELETE_BREW_FINISHED_GOODS_REQUEST =
    "DELETE_BREW_FINISHED_GOODS_REQUEST";
export const DELETE_BREW_FINISHED_GOODS_SUCCESS =
    "DELETE_BREW_FINISHED_GOODS_SUCCESS";
export const DELETE_BREW_FINISHED_GOODS_FAILURE =
    "DELETE_BREW_FINISHED_GOODS_FAILURE";
export const SET_BREW_FINISHED_GOODS = "SET_BREW_FINISHED_GOODS";
export const RESET_BREW_FINISHED_GOODS = "RESET_BREW_FINISHED_GOODS";
export const SET_FINISHED_GOODS_PAGE_INDEX = "SET_FINISHED_GOODS_PAGE_INDEX";
export const SET_FINISHED_GOODS_PAGE_SIZE = "SET_FINISHED_GOODS_PAGE_SIZE";
