export const FETCH_QUANTITY_UNITS_REQUEST = "FETCH_QUANTITY_UNITS_REQUEST";
export const FETCH_QUANTITY_UNITS_SUCCESS = "FETCH_QUANTITY_UNITS_SUCCESS";
export const FETCH_QUANTITY_UNITS_FAILURE = "FETCH_QUANTITY_UNITS_FAILURE";
