version: "3.3"
services:
  helm:
    image: alpine/helm:3.9.2
    container_name: brewcraft_helm
    working_dir: /usr/code/app/deployment
    network_mode: "host" # Hack: This is needed so the helm can access the host's minikube IP
    volumes:
      - ${PWD}:/usr/code/app
      - ${HOME}/.kube:/root/.kube
      - ${HOME}/.minikube/:${HOME}/.minikube
