export const FETCH_ALL_SUPPLIER_CONTACTS_REQUEST =
    "FETCH_ALL_SUPPLIER_CONTACTS_REQUEST";
export const FETCH_ALL_SUPPLIER_CONTACTS_SUCCESS =
    "FETCH_ALL_SUPPLIER_CONTACTS_SUCCESS";
export const FETCH_ALL_SUPPLIER_CONTACTS_FAILURE =
    "FETCH_ALL_SUPPLIER_CONTACTS_FAILURE";
export const FETCH_SUPPLIER_CONTACTS_REQUEST =
    "FETCH_SUPPLIER_CONTACTS_REQUEST";
export const FETCH_SUPPLIER_CONTACTS_SUCCESS =
    "FETCH_SUPPLIER_CONTACTS_SUCCESS";
export const FETCH_SUPPLIER_CONTACTS_FAILURE =
    "FETCH_SUPPLIER_CONTACTS_FAILURE";
export const SET_SUPPLIER_CONTACTS_DETAILS = "SET_SUPPLIER_CONTACTS_DETAILS";
export const SET_SUPPLIER_CONTACTS_PAGE_INDEX =
    "SET_SUPPLIER_CONTACTS_PAGE_INDEX";
export const SET_SUPPLIER_CONTACTS_PAGE_SIZE =
    "SET_SUPPLIER_CONTACTS_PAGE_SIZE";
export const SET_SUPPLIER_CONTACTS_SELECTED_COMPANY =
    "SET_SUPPLIER_CONTACTS_SELECTED_COMPANY";
