export const FETCH_INVENTORY_PROCUREMENTS_QUANTITY_REQUEST = "FETCH_INVENTORY_PROCUREMENTS_QUANTITY_REQUEST";
export const FETCH_INVENTORY_STOCK_QUANTITY_REQUEST = "FETCH_INVENTORY_STOCK_QUANTITY_REQUEST";
export const SET_INVENTORY_PROCUREMENTS_QUANTITY_DETAILS = "SET_INVENTORY_PROCUREMENTS_QUANTITY_DETAILS";
export const SET_INVENTORY_STOCK_QUANTITY_DETAILS = "SET_INVENTORY_STOCK_QUANTITY_DETAILS";
export const SET_MATERIALS_PAGE_INDEX = "SET_MATERIALS_PAGE_INDEX";
export const SET_MATERIALS_PAGE_SIZE = "SET_MATERIALS_PAGE_SIZE";
