export const FETCH_MINI_CARD_BREWS_MIXTURES_REQUEST =
    "FETCH_MINI_CARD_BREWS_MIXTURES_REQUEST";
export const SET_MINI_CARD_DETAILS = "SET_MINI_CARD_DETAILS";
export const FETCH_MINI_CARD_BREWS_MIXTURES_SUCCESS =
    "FETCH_MINI_CARD_BREWS_MIXTURES_SUCCESS";
export const FETCH_MINI_CARD_BREWS_MIXTURES_FAILURE =
    "FETCH_MINI_CARD_BREWS_MIXTURES_FAILURE";
export const FETCH_MINI_CARD_FINISHED_GOODS_REQUEST =
    "FETCH_MINI_CARD_FINISHED_GOODS_REQUEST";
export const FETCH_MINI_CARD_FINISHED_GOODS_SUCCESS =
    "FETCH_MINI_CARD_FINISHED_GOOD_SUCCESS";
export const FETCH_MINI_CARD_FINISHED_GOODS_FAILURE =
    "FETCH_MINI_CARD_FINISHED_GOODS_FAILURE";
