export const FETCH_BATCH_BY_ID_REQUEST = "FETCH_BATCH_BY_ID_REQUEST";
export const FETCH_BATCH_BY_ID_SUCCESS = "FETCH_BATCH_BY_ID_SUCCESS";
export const FETCH_BATCH_BY_ID_FAILURE = "FETCH_BATCH_BY_ID_FAILURE";
export const ADD_BATCH_REQUEST = "ADD_BATCH_REQUEST";
export const ADD_BATCH_SUCCESS = "ADD_BATCH_SUCCESS";
export const ADD_BATCH_FAILURE = "ADD_BATCH_FAILURE";
export const EDIT_BATCH_REQUEST = "EDIT_BATCH_REQUEST";
export const EDIT_BATCH_SUCCESS = "EDIT_BATCH_SUCCESS";
export const EDIT_BATCH_FAILURE = "EDIT_BATCH_FAILURE";
export const DELETE_BATCH_REQUEST = "DELETE_BATCH_REQUEST";
export const DELETE_BATCH_SUCCESS = "DELETE_BATCH_SUCCESS";
export const DELETE_BATCH_FAILURE = "DELETE_BATCH_FAILURE";
export const SET_BATCH_DETAILS = "SET_BATCH_DETAILS";
export const RESET_BATCH_DETAILS = "RESET_BATCH_DETAILS";
export const SET_BATCH_INVALID_CATEGORY = "SET_BATCH_INVALID_CATEGORY";
export const SET_BATCH_INVALID_NAME = "SET_BATCH_INVALID_NAME";
export const SET_BATCH_INVALID_PARENT_BREW = "SET_BATCH_INVALID_PARENT_BREW";
export const SET_BATCH_INVALID_PRODUCT = "SET_BATCH_INVALID_PRODUCT";
export const SET_BATCH_INVALID_STARTED_AT = "SET_BATCH_INVALID_STARTED_AT";
export const SET_BATCH_INVALID_ENDED_AT = "SET_BATCH_INVALID_ENDED_AT";
export const SET_BATCH_INVALID_DESCRIPTION = "SET_BATCH_INVALID_DESCRIPTION";
export const SET_INITIAL_BATCH_DETAILS = "SET_INITIAL_BATCH_DETAILS";
export const VALIDATE_BREW_FIELDS = "VALIDATE_BREW_FIELDS";
export const VALIDATE_BREW_FIELDS_SUCCESS = "VALIDATE_BREW_FIELDS_SUCCESS";
export const FETCH_ALL_BREW_STAGE_REQUEST = "FETCH_ALL_BREW_STAGE_REQUEST";
export const FETCH_ALL_BREW_STAGE_SUCCESS = "FETCH_ALL_BREW_STAGE_SUCCESS";
export const FETCH_ALL_BREW_STAGE_FAILURE = "FETCH_ALL_BREW_STAGE_FAILURE";
export const FETCH_BREW_STAGE_BY_BREW_ID_REQUEST =
    "FETCH_BREW_STAGE_BY_BREW_ID_REQUEST";
export const FETCH_BREW_STAGES_BY_BREW_ID_SUCCESS =
    "FETCH_BREW_STAGES_BY_BREW_ID_SUCCESS";
export const FETCH_BREW_STAGES_BY_BREW_ID_FAILURE =
    "FETCH_BREW_STAGES_BY_BREW_ID_FAILURE";
export const ADD_BREW_STAGE_REQUEST = "ADD_BREW_STAGE_REQUEST";
export const ADD_BREW_STAGE_SUCCESS = "ADD_BREW_STAGE_SUCCESS";
export const ADD_BREW_STAGE_FAILURE = "ADD_BREW_STAGE_FAILURE";
export const EDIT_BREW_STAGES_REQUEST = "EDIT_BREW_STAGES_REQUEST";
export const EDIT_BREW_STAGES_SUCCESS = "EDIT_BREW_STAGES_SUCCESS";
export const EDIT_BREW_STAGES_FAILURE = "EDIT_BREW_STAGES_FAILURE";
export const DELETE_BREW_STAGE_REQUEST = "DELETE_BREW_STAGE_REQUEST";
export const DELETE_BREW_STAGE_SUCCESS = "DELETE_BREW_STAGE_SUCCESS";
export const DELETE_BREW_STAGE_FAILURE = "DELETE_BREW_STAGE_FAILURE";
export const SET_BREW_STAGES = "SET_BREW_STAGES";
export const RESET_BREW_STAGES = "RESET_BREW_STAGES";

export const SET_MASH_STAGE_DETAILS = "SET_MASH_STAGE_DETAILS";
export const RESET_MASH_STAGE_DETAILS = "RESET_MASH_STAGE_DETAILS";

export const SET_KETTLE_STAGE_DETAILS = "SET_KETTLE_STAGE_DETAILS";
export const RESET_KETTLE_STAGE_DETAILS = "RESET_KETTLE_STAGE_DETAILS";

export const SET_WHIRLPOOL_STAGE_DETAILS = "SET_WHIRLPOOL_STAGE_DETAILS";
export const RESET_WHIRLPOOL_STAGE_DETAILS = "RESET_WHIRLPOOL_STAGE_DETAILS";

export const SET_TRANSFER_STAGE_DETAILS = "SET_TRANSFER_STAGE_DETAILS";
export const RESET_TRANSFER_STAGE_DETAILS = "RESET_TRANSFER_STAGE_DETAILS";

export const SET_FERMENT_STAGE_DETAILS = "SET_FERMENT_STAGE_DETAILS";
export const RESET_FERMENT_STAGE_DETAILS = "RESET_FERMENT_STAGE_DETAILS";

export const SET_CONDITION_STAGE_DETAILS = "SET_CONDITION_STAGE_DETAILS";
export const RESET_CONDITION_STAGE_DETAILS = "RESET_CONDITION_STAGE_DETAILS";

export const SET_BRITE_TANK_STAGE_DETAILS = "SET_BRITE_TANK_STAGE_DETAILS";
export const RESET_BRITE_TANK_STAGE_DETAILS = "RESET_BRITE_TANK_STAGE_DETAILS";

export const TRANSFER_TO_FERMENT_STAGE_REQUEST =
    "TRANSFER_TO_FERMENT_STAGE_REQUEST";
export const TRANSFER_TO_FERMENT_STAGE_SUCCESS =
    "TRANSFER_TO_FERMENT_STAGE_SUCCESS";
export const TRANSFER_TO_FERMENT_STAGE_FAILURE =
    "TRANSFER_TO_FERMENT_STAGE_FAILURE";
