export const FETCH_FINISHED_GOODS = "FETCH_FINISHED_GOODS";

export const FETCH_FERMENT_FINISHED_GOODS = "FETCH_FERMENT_FINISHED_GOODS";
export const SET_FERMENT_FINISHED_GOODS = "SET_FERMENT_FINISHED_GOODS";
export const SAVE_FERMENT_FINISHED_GOODS = "SAVE_FERMENT_FINISHED_GOODS";

export const SET_CONDITION_FINISHED_GOODS = "SET_CONDITION_FINISHED_GOODS";
export const SET_BRITE_TANK_FINISHED_GOODS = "SET_BRITE_TANK_FINISHED_GOODS";
