export const FETCH_FINISHED_GOOD_BY_ID_REQUEST =
    "FETCH_FINISHED_GOOD_BY_ID_REQUEST";
export const FETCH_FINISHED_GOOD_BY_ID_SUCCESS =
    "FETCH_FINISHED_GOOD_BY_ID_SUCCESS";
export const FETCH_FINISHED_GOOD_BY_ID_FAILURE =
    "FETCH_FINISHED_GOOD_BY_ID_FAILURE";
export const FETCH_FINISHED_GOODS_BY_BREW_ID_REQUEST =
    "FETCH_FINISHED_GOODS_BY_BREW_ID_REQUEST";
export const FETCH_FINISHED_GOODS_BY_BREW_ID_SUCCESS =
    "FETCH_FINISHED_GOODS_BY_BREW_ID_REQUEST_SUCCESS";
export const FETCH_FINISHED_GOODS_BY_BREW_ID_FAILURE =
    "FETCH_FINISHED_GOODS_BY_BREW_ID_FAILURE";
export const FETCH_FINISHED_GOODS_REQUEST = "FETCH_FINISHED_GOODS_REQUEST";
export const FETCH_FINISHED_GOODS_SUCCESS = "FETCH_FINISHED_GOODS_SUCCESS";
export const FETCH_FINISHED_GOODS_FAILURE = "FETCH_FINISHED_GOODS_FAILURE";
export const FETCH_FINISHED_GOODS_BY_MIXTURE_ID_REQUEST =
    "FETCH_FINISHED_GOODS_BY_MIXTURE_ID_REQUEST";
export const FETCH_FINISHED_GOODS_BY_MIXTURE_ID_SUCCESS =
    "FETCH_FINISHED_GOODS_BY_MIXTURE_ID_SUCCESS";
export const FETCH_FINISHED_GOODS_BY_MIXTURE_ID_FAILURE =
    "FETCH_FINISHED_GOODS_BY_MIXTURE_ID_FAILURE";
export const SAVE_FINISHED_GOODS_REQUEST = "SAVE_FINISHED_GOODS_REQUEST";
export const SAVE_FINISHED_GOODS_SUCCESS = "SAVE_FINISHED_GOODS_SUCCESS";
export const SAVE_FINISHED_GOODS_FAILURE = "SAVE_FINISHEODS_FAILURE";
export const DELETE_FINISHED_GOODS_REQUEST =
    "DELETE_FINISHD_GOED_GOODS_REQUEST";
export const DELETE_FINISHED_GOODS_SUCCESS = "DELETE_FINISHED_GOODS_SUCCESS";
export const DELETE_FINISHED_GOODS_FAILURE = "DELETE_FINISHED_GOODS_FAILURE";
export const SET_FINISHED_GOODS = "SET_FINISHED_GOODS";
export const SET_FINISHED_GOODS_PAGE_INDEX = "SET_FINISHED_GOODS_PAGE_INDEX";
export const SET_FINISHED_GOODS_PAGE_SIZE = "SET_FINISHED_GOODS_PAGE_SIZE";

// depricated
export const FETCH_FINISHED_GOODS = "FETCH_FINISHED_GOODS";
export const SAVE_FINISHED_GOODS = "SAVE_FINISHED_GOODS";
export const DELETE_FINISHED_GOODS = "DELETE_FINISHED_GOODS";
export const SAVE_FINISHED_GOODS_ERROR = "SAVE_FINISHED_GOODS_ERROR";
export const DELETE_FINISHED_GOODS_ERROR = "DELETE_FINISHED_GOODS_ERROR";
export const RESET_FINISHED_GOODS_DETAILS = "RESET_FINISHED_GOODS_DETAILS";
