export const FETCH_PURCHASES_REQUEST = "FETCH_PURCHASES_REQUEST";
export const FETCH_PURCHASES_SUCCESS = "FETCH_PURCHASES_SUCCESS";
export const FETCH_PURCHASES_FAIL = "FETCH_PURCHASES_FAIL";

export const FETCH_PURCHASE_REQUEST = "FETCH_PURCHASE_REQUEST";
export const FETCH_PURCHASE_SUCCESS = "FETCH_PURCHASE_SUCCESS";
export const FETCH_PURCHASE_FAIL = "FETCH_PURCHASE_FAIL";

export const CREATE_PURCHASE_REQUEST = "FETCH_PURCHASE_REQUEST";
export const CREATE_PURCHASE_SUCCESS = "FETCH_PURCHASE_SUCCESS";
export const CREATE_PURCHASE_FAIL = "FETCH_PURCHASE_FAIL";

export const UPDATE_PURCHASE_REQUEST = "UPDATE_PURCHASE_REQUEST";
export const UPDATE_PURCHASE_SUCCESS = "UPDATE_PURCHASE_SUCCESS";
export const UPDATE_PURCHASE_FAIL = "UPDATE_PURCHASE_FAIL";

export const DELETE_PURCHASE_REQUEST = "DELETE_PURCHASE_REQUEST";
export const DELETE_PURCHASE_SUCCESS = "DELETE_PURCHASE_SUCCESS";
export const DELETE_PURCHASE_FAIL = "DELETE_PURCHASE_FAIL";