export const SET_BATCH_DETAILS = "SET_BATCH_DETAILS";
export const FETCH_BATCH = "FETCH_BATCH";
export const CREATE_BATCH = "CREATE_BATCH";
export const UPDATE_BATCH = "UPDATE_BATCH";
export const DELETE_BATCH = "DELETE_BATCH";
export const INVALID_NAME = "INVALID_NAME";
export const INVALID_DESCRIPTION = "INVALID_DESCRIPTION";
export const RESET_BATCH_DETAILS = "RESET_BATCH_DETAILS";