export const FETCH_BATCH_MIXTURE_RECORDINGS_REQUEST =
    "FETCH_BATCH_MIXTURE_RECORDINGS_REQUEST";
export const FETCH_BATCH_MIXTURE_RECORDINGS_BY_ID_REQUEST =
    "FETCH_BATCH_MIXTURE_RECORDINGS_BY_ID_REQUEST";
export const FETCH_BATCH_MIXTURE_RECORDINGS_SUCCESS =
    "FETCH_BATCH_MIXTURE_RECORDINGS_SUCCESS";
export const FETCH_BATCH_MIXTURE_RECORDINGS_FAILURE =
    "FETCH_BATCH_MIXTURE_RECORDINGS_FAILURE";
export const EDIT_BATCH_MIXTURE_RECORDINGS = "EDIT_BATCH_MIXTURE_RECORDINGS";
export const EDIT_BATCH_MIXTURE_RECORDINGS_SUCCESS =
    "EDIT_BATCH_MIXTURE_RECORDINGS_SUCCESS";
export const EDIT_BATCH_MIXTURE_RECORDINGS_FAILURE =
    "EDIT_BATCH_MIXTURE_RECORDINGS_FAILURE";
export const UPDATE_BATCH_MIXTURE_RECORDINGS_REQUEST =
    "UPDATE_BATCH_MIXTURE_RECORDINGS_REQUEST";
export const UPDATE_BATCH_MIXTURE_RECORDINGS_SUCCESS =
    "UPDATE_BATCH_MIXTURE_RECORDINGS_SUCCESS";
export const UPDATE_BATCH_MIXTURE_RECORDINGS_FAILURE =
    "UPDATE_BATCH_MIXTURE_RECORDINGS_FAILURE";
export const DELETE_BATCH_MIXTURE_RECORDINGS_REQUEST =
    "DELETE_BATCH_MIXTURE_RECORDINGS_REQUEST";
export const DELETE_BATCH_MIXTURE_RECORDINGS_SUCCESS =
    "DELETE_BATCH_MIXTURE_RECORDINGS_SUCCESS";
export const DELETE_BATCH_MIXTURE_RECORDINGS_FAILURE =
    "DELETE_BATCH_MIXTURE_RECORDINGS_FAILURE";
export const SET_BATCH_MIXTURE_RECORDINGS = "SET_BATCH_MIXTURE_RECORDINGS";
export const RESET_BATCH_MIXTURE_RECORDINGS = "RESET_BATCH_MIXTURE_RECORDINGS";
