export const FETCH_BREW_MIXTURE_RECORDINGS_REQUEST =
    "FETCH_BREW_MIXTURE_RECORDINGS_REQUEST";
export const FETCH_BREW_MIXTURE_RECORDINGS_BY_ID_REQUEST =
    "FETCH_BREW_MIXTURE_RECORDINGS_BY_ID_REQUEST";
export const FETCH_BREW_MIXTURE_RECORDINGS_SUCCESS =
    "FETCH_BREW_MIXTURE_RECORDINGS_SUCCESS";
export const FETCH_BREW_MIXTURE_RECORDINGS_FAILURE =
    "FETCH_BREW_MIXTURE_RECORDINGS_FAILURE";
export const EDIT_BREW_MIXTURE_RECORDINGS_REQUEST =
    "EDIT_BREW_MIXTURE_RECORDINGS_REQUEST";
export const EDIT_BREW_MIXTURE_RECORDINGS_SUCCESS =
    "EDIT_BREW_MIXTURE_RECORDINGS_SUCCESS";
export const EDIT_BREW_MIXTURE_RECORDINGS_FAILURE =
    "EDIT_BREW_MIXTURE_RECORDINGS_FAILURE";
export const DELETE_BREW_MIXTURE_RECORDINGS_REQUEST =
    "DELETE_BREW_MIXTURE_RECORDINGS_REQUEST";
export const DELETE_BREW_MIXTURE_RECORDINGS_SUCCESS =
    "DELETE_BREW_MIXTURE_RECORDINGS_SUCCESS";
export const DELETE_BREW_MIXTURE_RECORDINGS_FAILURE =
    "DELETE_BREW_MIXTURE_RECORDINGS_FAILURE";
export const SET_BREW_MIXTURE_RECORDINGS = "SET_BREW_MIXTURE_RECORDINGS";
export const RESET_BREW_MIXTURE_RECORDINGS = "RESET_BREW_MIXTURE_RECORDINGS";
