export const FETCH_MIXTURE_RECORDINGS_BY_BREW_ID_REQUEST =
    "FETCH_MIXTURE_RECORDINGS_BY_BREW_ID_REQUEST";
export const FETCH_MIXTURE_RECORDINGS_BY_ID_REQUEST =
    "FETCH_MIXTURE_RECORDINGS_BY_ID_REQUEST";
export const FETCH_MIXTURE_RECORDINGS_BY_BREW_ID_SUCCESS =
    "FETCH_MIXTURE_RECORDINGS_BY_BREW_ID_SUCCESS";
export const FETCH_MIXTURE_RECORDINGS_BY_BREW_ID_FAILURE =
    "FETCH_MIXTURE_RECORDINGS_BY_BREW_ID_FAILURE";
export const EDIT_BREW_MIXTURE_RECORDINGS_REQUEST =
    "EDIT_BREW_MIXTURE_RECORDINGS_REQUEST";
export const EDIT_BREW_MIXTURE_RECORDINGS_SUCCESS =
    "EDIT_BREW_MIXTURE_RECORDINGS_SUCCESS";
export const EDIT_BREW_MIXTURE_RECORDINGS_FAILURE =
    "EDIT_BREW_MIXTURE_RECORDINGS_FAILURE";
export const DELETE_BREW_MIXTURE_RECORDINGS_REQUEST =
    "DELETE_BREW_MIXTURE_RECORDINGS_REQUEST";
export const DELETE_BREW_MIXTURE_RECORDINGS_SUCCESS =
    "DELETE_BREW_MIXTURE_RECORDINGS_SUCCESS";
export const DELETE_BREW_MIXTURE_RECORDINGS_FAILURE =
    "DELETE_BREW_MIXTURE_RECORDINGS_FAILURE";
export const SET_BREW_MIXTURE_RECORDINGS = "SET_BREW_MIXTURE_RECORDINGS";
export const RESET_BREW_MIXTURE_RECORDINGS = "RESET_BREW_MIXTURE_RECORDINGS";

export const FETCH_KETTLE_MIXTURE_RECORDING_BY_MIXTURE_ID_REQUEST =
    "FETCH_KETTLE_MIXTURE_RECORDING_BY_MIXTURE_ID_REQUEST";
export const ADD_KETTLE_MIXTURE_RECORDING_REQUEST =
    "ADD_KETTLE_MIXTURE_RECORDING_REQUEST";
export const ADD_KETTLE_MIXTURE_RECORDING_SUCCESS =
    "ADD_KETTLE_MIXTURE_RECORDING_SUCCESS";
export const ADD_KETTLE_MIXTURE_RECORDING_FAILURE =
    "ADD_KETTLE_MIXTURE_RECORDING_FAILURE";
export const EDIT_KETTLE_MIXTURE_RECORDING_REQUEST =
    "EDIT_KETTLE_MIXTURE_RECORDING_REQUEST";
export const EDIT_KETTLE_MIXTURE_RECORDING_SUCCESS =
    "EDIT_KETTLE_MIXTURE_RECORDING_SUCCESS";
export const EDIT_KETTLE_MIXTURE_RECORDING_FAILURE =
    "EDIT_KETTLE_MIXTURE_RECORDING_FAILURE";
export const DELETE_KETTLE_MIXTURE_RECORDING_REQUEST =
    "DELETE_KETTLE_MIXTURE_RECORDING_REQUEST";
export const DELETE_KETTLE_MIXTURE_RECORDING_SUCCESS =
    "DELETE_KETTLE_MIXTURE_RECORDING_SUCCESS";
export const DELETE_KETTLE_MIXTURE_RECORDING_FAILURE =
    "DELETE_KETTLE_MIXTURE_RECORDING_FAILURE";
export const SET_KETTLE_MIXTURE_RECORDING_DETAILS =
    "SET_KETTLE_MIXTURE_RECORDING_DETAILS";
export const RESET_KETTLE_MIXTURE_RECORDING_DETAILS =
    "RESET_KETTLE_MIXTURE_RECORDING_DETAILS";

export const FETCH_FERMENT_MIXTURE_RECORDING_BY_MIXTURE_ID_REQUEST =
    "FETCH_FERMENT_MIXTURE_RECORDING_BY_MIXTURE_ID_REQUEST";
export const ADD_FERMENT_MIXTURE_RECORDING_REQUEST =
    "ADD_FERMENT_MIXTURE_RECORDING_REQUEST";
export const ADD_FERMENT_MIXTURE_RECORDING_SUCCESS =
    "ADD_FERMENT_MIXTURE_RECORDING_SUCCESS";
export const ADD_FERMENT_MIXTURE_RECORDING_FAILURE =
    "ADD_FERMENT_MIXTURE_RECORDING_FAILURE";
export const EDIT_FERMENT_MIXTURE_RECORDING_REQUEST =
    "EDIT_FERMENT_MIXTURE_RECORDING_REQUEST";
export const EDIT_FERMENT_MIXTURE_RECORDING_SUCCESS =
    "EDIT_FERMENT_MIXTURE_RECORDING_SUCCESS";
export const EDIT_FERMENT_MIXTURE_RECORDING_FAILURE =
    "EDIT_FERMENT_MIXTURE_RECORDING_FAILURE";
export const DELETE_MIXTURE_RECORDING_REQUEST =
    "DELETE_MIXTURE_RECORDING_REQUEST";
export const DELETE_FERMENT_MIXTURE_RECORDING_SUCCESS =
    "DELETE_FERMENT_MIXTURE_RECORDING_SUCCESS";
export const DELETE_FERMENT_MIXTURE_RECORDING_FAILURE =
    "DELETE_FERMENT_MIXTURE_RECORDING_FAILURE";
export const SET_FERMENT_MIXTURE_RECORDING_DETAILS =
    "SET_FERMENT_MIXTURE_RECORDING_DETAILS";
export const RESET_FERMENT_MIXTURE_RECORDING_DETAILS =
    "RESET_FERMENT_MIXTURE_RECORDING_DETAILS";

export const FETCH_TRANSFER_MIXTURE_RECORDING_BY_MIXTURE_ID_REQUEST =
    "FETCH_TRANSFER_MIXTURE_RECORDING_BY_MIXTURE_ID_REQUEST";
export const ADD_TRANSFER_MIXTURE_RECORDING_REQUEST =
    "ADD_TRANSFER_MIXTURE_RECORDING_REQUEST";
export const ADD_TRANSFER_MIXTURE_RECORDING_SUCCESS =
    "ADD_TRANSFER_MIXTURE_RECORDING_SUCCESS";
export const ADD_TRANSFER_MIXTURE_RECORDING_FAILURE =
    "ADD_TRANSFER_MIXTURE_RECORDING_FAILURE";
export const EDIT_TRANSFER_MIXTURE_RECORDING_REQUEST =
    "EDIT_TRANSFER_MIXTURE_RECORDING_REQUEST";
export const EDIT_TRANSFER_MIXTURE_RECORDING_SUCCESS =
    "EDIT_TRANSFER_MIXTURE_RECORDING_SUCCESS";
export const EDIT_TRANSFER_MIXTURE_RECORDING_FAILURE =
    "EDIT_TRANSFER_MIXTURE_RECORDING_FAILURE";
export const DELETE_TRANSFER_MIXTURE_RECORDING_REQUEST =
    "DELETE_TRANSFER_MIXTURE_RECORDING_REQUEST";
export const DELETE_TRANSFER_MIXTURE_RECORDING_SUCCESS =
    "DELETE_TRANSFER_MIXTURE_RECORDING_SUCCESS";
export const DELETE_TRANSFER_MIXTURE_RECORDING_FAILURE =
    "DELETE_TRANSFER_MIXTURE_RECORDING_FAILURE";
export const SET_TRANSFER_MIXTURE_RECORDING_DETAILS =
    "SET_TRANSFER_MIXTURE_RECORDING_DETAILS";
export const RESET_TRANSFER_MIXTURE_RECORDING_DETAILS =
    "RESET_TRANSFER_MIXTURE_RECORDING_DETAILS";

export const FETCH_WHIRLPOOL_MIXTURE_RECORDING_BY_MIXTURE_ID_REQUEST =
    "FETCH_WHIRLPOOL_MIXTURE_RECORDING_BY_MIXTURE_ID_REQUEST";
export const ADD_WHIRLPOOL_MIXTURE_RECORDING_REQUEST =
    "ADD_WHIRLPOOL_MIXTURE_RECORDING_REQUEST";
export const ADD_WHIRLPOOL_MIXTURE_RECORDING_SUCCESS =
    "ADD_WHIRLPOOL_MIXTURE_RECORDING_SUCCESS";
export const ADD_WHIRLPOOL_MIXTURE_RECORDING_FAILURE =
    "ADD_WHIRLPOOL_MIXTURE_RECORDING_FAILURE";
export const EDIT_WHIRLPOOL_MIXTURE_RECORDING_REQUEST =
    "EDIT_WHIRLPOOL_MIXTURE_RECORDING_REQUEST";
export const EDIT_WHIRLPOOL_MIXTURE_RECORDING_SUCCESS =
    "EDIT_WHIRLPOOL_MIXTURE_RECORDING_SUCCESS";
export const EDIT_WHIRLPOOL_MIXTURE_RECORDING_FAILURE =
    "EDIT_WHIRLPOOL_MIXTURE_RECORDING_FAILURE";
export const DELETE_WHIRLPOOL_MIXTURE_RECORDING_REQUEST =
    "DELETE_WHIRLPOOL_MIXTURE_RECORDING_REQUEST";
export const DELETE_WHIRLPOOL_MIXTURE_RECORDING_SUCCESS =
    "DELETE_WHIRLPOOL_MIXTURE_RECORDING_SUCCESS";
export const DELETE_WHIRLPOOL_MIXTURE_RECORDING_FAILURE =
    "DELETE_WHIRLPOOL_MIXTURE_RECORDING_FAILURE";
export const SET_WHIRLPOOL_MIXTURE_RECORDING_DETAILS =
    "SET_WHIRLPOOL_MIXTURE_RECORDING_DETAILS";
export const RESET_WHIRLPOOL_MIXTURE_RECORDING_DETAILS =
    "RESET_WHIRLPOOL_MIXTURE_RECORDING_DETAILS";

export const FETCH_CONDITION_MIXTURE_RECORDING_BY_MIXTURE_ID_REQUEST =
    "FETCH_CONDITION_MIXTURE_RECORDING_BY_MIXTURE_ID_REQUEST";
export const ADD_CONDITION_MIXTURE_RECORDING_REQUEST =
    "ADD_CONDITION_MIXTURE_RECORDING_REQUEST";
export const ADD_CONDITION_MIXTURE_RECORDING_SUCCESS =
    "ADD_CONDITION_MIXTURE_RECORDING_SUCCESS";
export const ADD_CONDITION_MIXTURE_RECORDING_FAILURE =
    "ADD_CONDITION_MIXTURE_RECORDING_FAILURE";
export const EDIT_CONDITION_MIXTURE_RECORDING_REQUEST =
    "EDIT_CONDITION_MIXTURE_RECORDING_REQUEST";
export const EDIT_CONDITION_MIXTURE_RECORDING_SUCCESS =
    "EDIT_CONDITION_MIXTURE_RECORDING_SUCCESS";
export const EDIT_CONDITION_MIXTURE_RECORDING_FAILURE =
    "EDIT_CONDITION_MIXTURE_RECORDING_FAILURE";
export const DELETE_CONDITION_MIXTURE_RECORDING_REQUEST =
    "DELETE_CONDITION_MIXTURE_RECORDING_REQUEST";
export const DELETE_CONDITION_MIXTURE_RECORDING_SUCCESS =
    "DELETE_CONDITION_MIXTURE_RECORDING_SUCCESS";
export const DELETE_CONDITION_MIXTURE_RECORDING_FAILURE =
    "DELETE_CONDITION_MIXTURE_RECORDING_FAILURE";
export const SET_CONDITION_MIXTURE_RECORDING_DETAILS =
    "SET_CONDITION_MIXTURE_RECORDING_DETAILS";
export const RESET_CONDITION_MIXTURE_RECORDING_DETAILS =
    "RESET_CONDITION_MIXTURE_RECORDING_DETAILS";

export const FETCH_BRITE_TANK_MIXTURE_RECORDING_BY_MIXTURE_ID_REQUEST =
    "FETCH_BRITE_TANK_MIXTURE_RECORDING_BY_MIXTURE_ID_REQUEST";
export const ADD_BRITE_TANK_MIXTURE_RECORDING_REQUEST =
    "ADD_BRITE_TANK_MIXTURE_RECORDING_REQUEST";
export const ADD_BRITE_TANK_MIXTURE_RECORDING_SUCCESS =
    "ADD_BRITE_TANK_MIXTURE_RECORDING_SUCCESS";
export const ADD_BRITE_TANK_MIXTURE_RECORDING_FAILURE =
    "ADD_BRITE_TANK_MIXTURE_RECORDING_FAILURE";
export const EDIT_BRITE_TANK_MIXTURE_RECORDING_REQUEST =
    "EDIT_BRITE_TANK_MIXTURE_RECORDING_REQUEST";
export const EDIT_BRITE_TANK_MIXTURE_RECORDING_SUCCESS =
    "EDIT_BRITE_TANK_MIXTURE_RECORDING_SUCCESS";
export const EDIT_BRITE_TANK_MIXTURE_RECORDING_FAILURE =
    "EDIT_BRITE_TANK_MIXTURE_RECORDING_FAILURE";
export const DELETE_BRITE_TANK_MIXTURE_RECORDING_REQUEST =
    "DELETE_BRITE_TANK_MIXTURE_RECORDING_REQUEST";
export const DELETE_BRITE_TANK_MIXTURE_RECORDING_SUCCESS =
    "DELETE_BRITE_TANK_MIXTURE_RECORDING_SUCCESS";
export const DELETE_BRITE_TANK_MIXTURE_RECORDING_FAILURE =
    "DELETE_BRITE_TANK_MIXTURE_RECORDING_FAILURE";
export const SET_BRITE_TANK_MIXTURE_RECORDING_DETAILS =
    "SET_BRITE_TANK_MIXTURE_RECORDING_DETAILS";
export const RESET_BRITE_TANK_MIXTURE_RECORDING_DETAILS =
    "RESET_BRITE_TANK_MIXTURE_RECORDING_DETAILS";
