export const FETCH_EQUIPMENT_ITEM_REQUEST = "FETCH_EQUIPMENT_ITEM_REQUEST";
export const FETCH_EQUIPMENT_ITEM_SUCCESS = "FETCH_EQUIPMENT_ITEM_SUCCESS";
export const FETCH_EQUIPMENT_ITEM_FAILURE = "FETCH_EQUIPMENT_ITEM_FAILURE";

export const CREATE_EQUIPMENT_ITEM_REQUEST = "CREATE_EQUIPMENT_ITEM_REQUEST";
export const CREATE_EQUIPMENT_ITEM_SUCCESS = "CREATE_EQUIPMENT_ITEM_SUCCESS";
export const CREATE_EQUIPMENT_ITEM_FAILURE = "CREATE_EQUIPMENT_ITEM_FAILURE";

export const UPDATE_EQUIPMENT_ITEM_REQUEST = "UPDATE_EQUIPMENT_ITEM_REQUEST";
export const UPDATE_EQUIPMENT_ITEM_SUCCESS = "UPDATE_EQUIPMENT_ITEM_SUCCESS";
export const UPDATE_EQUIPMENT_ITEM_FAILURE = "UPDATE_EQUIPMENT_ITEM_FAILURE";

export const DELETE_EQUIPMENT_ITEM_REQUEST = "DELETE_EQUIPMENT_ITEM_REQUEST";
export const DELETE_EQUIPMENT_ITEM_SUCCESS = "DELETE_EQUIPMENT_ITEM_SUCCESS";
export const DELETE_EQUIPMENT_ITEM_FAILURE = "DELETE_EQUIPMENT_ITEM_FAILURE";

export const SET_EQUIPMENT_ITEM = "SET_EQUIPMENT_ITEM";
export const RESET_EQUIPMENT_ITEM = "RESET_EQUIPMENT_ITEM";

export const VALIDATE_EQUIPMENT_ITEM = "VALIDATE_EQUIPMENT_ITEM";
export const VALIDATE_EQUIPMENT_ITEM_SUCCESS =
    "VALIDATE_EQUIPMENT_ITEM_SUCCESS";
export const VALIDATE_EQUIPMENT_ITEM_FAILURE =
    "VALIDATE_EQUIPMENT_ITEM_FAILURE";

export const FETCH_EQUIPMENT_REQUEST = "FETCH_EQUIPMENT_REQUEST";
export const FETCH_EQUIPMENT_SUCCESS = "FETCH_EQUIPMENT_SUCCESS";
export const FETCH_EQUIPMENT_FAILURE = "FETCH_EQUIPMENT_FAILURE";
export const SET_EQUIPMENT = "SET_EQUIPMENT";
