export const FETCH_MATERIAL_PORTION_BY_ID_REQUEST =
    "FETCH_MATERIAL_PORTION_BY_ID_REQUEST";
export const FETCH_MATERIAL_PORTION_BY_BREW_ID_REQUEST =
    "FETCH_MATERIAL_PORTION_BY_BREW_ID_REQUEST";
export const FETCH_MATERIAL_PORTIONS_BY_MIXTURE_ID_REQUEST =
    "FETCH_MATERIAL_PORTIONS_BY_MIXTURE_ID_REQUEST";
export const SET_MATERIAL_PORTION_DETAILS = "SET_MATERIAL_PORTION_DETAILS";

export const ADD_MASH_MATERIAL_PORTION_REQUEST =
    "ADD_MASH_MATERIAL_PORTION_REQUEST";
export const ADD_MASH_MATERIAL_PORTION_SUCCESS =
    "ADD_MASH_MATERIAL_PORTION_SUCCESS";
export const ADD_MASH_MATERIAL_PORTION_FAILURE =
    "ADD_MASH_MATERIAL_PORTION_FAILURE";
export const EDIT_MASH_MATERIAL_PORTION_REQUEST =
    "EDIT_MASH_MATERIAL_PORTION_REQUEST";
export const EDIT_MASH_MATERIAL_PORTION_SUCCESS =
    "EDIT_MASH_MATERIAL_PORTION_SUCCESS";
export const EDIT_MASH_MATERIAL_PORTION_FAILURE =
    "EDIT_MASH_MATERIAL_PORTION_FAILURE";
export const DELETE_MASH_MATERIAL_PORTION_REQUEST =
    "DELETE_MASH_MATERIAL_PORTION_REQUEST";
export const DELETE_MASH_MATERIAL_PORTION_SUCCESS =
    "DELETE_MASH_MATERIAL_PORTION_SUCCESS";
export const DELETE_MASH_MATERIAL_PORTION_FAILURE =
    "DELETE_MASH_MATERIAL_PORTION_FAILURE";
export const SET_MASH_MATERIAL_PORTION_DETAILS =
    "SET_MASH_MATERIAL_PORTION_DETAILS";
export const RESET_MASH_MATERIAL_PORTION_DETAILS =
    "RESET_MASH_MATERIAL_PORTION_DETAILS";

export const ADD_KETTLE_MATERIAL_PORTION_REQUEST =
    "ADD_KETTLE_MATERIAL_PORTION_REQUEST";
export const ADD_KETTLE_MATERIAL_PORTION_SUCCESS =
    "ADD_KETTLE_MATERIAL_PORTION_SUCCESS";
export const ADD_KETTLE_MATERIAL_PORTION_FAILURE =
    "ADD_KETTLE_MATERIAL_PORTION_FAILURE";
export const EDIT_KETTLE_MATERIAL_PORTION_REQUEST =
    "EDIT_KETTLE_MATERIAL_PORTION_REQUEST";
export const EDIT_KETTLE_MATERIAL_PORTION_SUCCESS =
    "EDIT_KETTLE_MATERIAL_PORTION_SUCCESS";
export const EDIT_KETTLE_MATERIAL_PORTION_FAILURE =
    "EDIT_KETTLE_MATERIAL_PORTION_FAILURE";
export const DELETE_KETTLE_MATERIAL_PORTION_REQUEST =
    "DELETE_KETTLE_MATERIAL_PORTION_REQUEST";
export const DELETE_KETTLE_MATERIAL_PORTION_SUCCESS =
    "DELETE_KETTLE_MATERIAL_PORTION_SUCCESS";
export const DELETE_KETTLE_MATERIAL_PORTION_FAILURE =
    "DELETE_KETTLE_MATERIAL_PORTION_FAILURE";
export const SET_KETTLE_MATERIAL_PORTION_DETAILS =
    "SET_KETTLE_MATERIAL_PORTION_DETAILS";
export const RESET_KETTLE_MATERIAL_PORTION_DETAILS =
    "RESET_KETTLE_MATERIAL_PORTION_DETAILS";

export const ADD_FERMENT_MATERIAL_PORTION_REQUEST =
    "ADD_FERMENT_MATERIAL_PORTION_REQUEST";
export const ADD_FERMENT_MATERIAL_PORTION_SUCCESS =
    "ADD_FERMENT_MATERIAL_PORTION_SUCCESS";
export const ADD_FERMENT_MATERIAL_PORTION_FAILURE =
    "ADD_FERMENT_MATERIAL_PORTION_FAILURE";
export const EDIT_FERMENT_MATERIAL_PORTION_REQUEST =
    "EDIT_FERMENT_MATERIAL_PORTION_REQUEST";
export const EDIT_FERMENT_MATERIAL_PORTION_SUCCESS =
    "EDIT_FERMENT_MATERIAL_PORTION_SUCCESS";
export const EDIT_FERMENT_MATERIAL_PORTION_FAILURE =
    "EDIT_FERMENT_MATERIAL_PORTION_FAILURE";
export const DELETE_FERMENT_MATERIAL_PORTION_REQUEST =
    "DELETE_FERMENT_MATERIAL_PORTION_REQUEST";
export const DELETE_FERMENT_MATERIAL_PORTION_SUCCESS =
    "DELETE_FERMENT_MATERIAL_PORTION_SUCCESS";
export const DELETE_FERMENT_MATERIAL_PORTION_FAILURE =
    "DELETE_FERMENT_MATERIAL_PORTION_FAILURE";
export const SET_FERMENT_MATERIAL_PORTION_DETAILS =
    "SET_FERMENT_MATERIAL_PORTION_DETAILS";
export const RESET_FERMENT_MATERIAL_PORTION_DETAILS =
    "RESET_FERMENT_MATERIAL_PORTION_DETAILS";

export const ADD_CONDITION_MATERIAL_PORTION_REQUEST =
    "ADD_CONDITION_MATERIAL_PORTION_REQUEST";
export const ADD_CONDITION_MATERIAL_PORTION_SUCCESS =
    "ADD_CONDITION_MATERIAL_PORTION_SUCCESS";
export const ADD_CONDITION_MATERIAL_PORTION_FAILURE =
    "ADD_CONDITION_MATERIAL_PORTION_FAILURE";
export const EDIT_CONDITION_MATERIAL_PORTION_REQUEST =
    "EDIT_CONDITION_MATERIAL_PORTION_REQUEST";
export const EDIT_CONDITION_MATERIAL_PORTION_SUCCESS =
    "EDIT_CONDITION_MATERIAL_PORTION_SUCCESS";
export const EDIT_CONDITION_MATERIAL_PORTION_FAILURE =
    "EDIT_CONDITION_MATERIAL_PORTION_FAILURE";
export const DELETE_CONDITION_MATERIAL_PORTION_REQUEST =
    "DELETE_CONDITION_MATERIAL_PORTION_REQUEST";
export const DELETE_CONDITION_MATERIAL_PORTION_SUCCESS =
    "DELETE_CONDITION_MATERIAL_PORTION_SUCCESS";
export const DELETE_CONDITION_MATERIAL_PORTION_FAILURE =
    "DELETE_CONDITION_MATERIAL_PORTION_FAILURE";
export const SET_CONDITION_MATERIAL_PORTION_DETAILS =
    "SET_CONDITION_MATERIAL_PORTION_DETAILS";
export const RESET_CONDITION_MATERIAL_PORTION_DETAILS =
    "RESET_CONDITION_MATERIAL_PORTION_DETAILS";

export const ADD_BRITE_TANK_MATERIAL_PORTION_REQUEST =
    "ADD_BRITE_TANK_MATERIAL_PORTION_REQUEST";
export const ADD_BRITE_TANK_MATERIAL_PORTION_SUCCESS =
    "ADD_BRITE_TANK_MATERIAL_PORTION_SUCCESS";
export const ADD_BRITE_TANK_MATERIAL_PORTION_FAILURE =
    "ADD_BRITE_TANK_MATERIAL_PORTION_FAILURE";
export const EDIT_BRITE_TANK_MATERIAL_PORTION_REQUEST =
    "EDIT_BRITE_TANK_MATERIAL_PORTION_REQUEST";
export const EDIT_BRITE_TANK_MATERIAL_PORTION_SUCCESS =
    "EDIT_BRITE_TANK_MATERIAL_PORTION_SUCCESS";
export const EDIT_BRITE_TANK_MATERIAL_PORTION_FAILURE =
    "EDIT_BRITE_TANK_MATERIAL_PORTION_FAILURE";
export const DELETE_BRITE_TANK_MATERIAL_PORTION_REQUEST =
    "DELETE_BRITE_TANK_MATERIAL_PORTION_REQUEST";
export const DELETE_BRITE_TANK_MATERIAL_PORTION_SUCCESS =
    "DELETE_BRITE_TANK_MATERIAL_PORTION_SUCCESS";
export const DELETE_BRITE_TANK_MATERIAL_PORTION_FAILURE =
    "DELETE_BRITE_TANK_MATERIAL_PORTION_FAILURE";
export const SET_BRITE_TANK_MATERIAL_PORTION_DETAILS =
    "SET_BRITE_TANK_MATERIAL_PORTION_DETAILS";
export const RESET_BRITE_TANK_MATERIAL_PORTION_DETAILS =
    "RESET_BRITE_TANK_MATERIAL_PORTION_DETAILS";
