export const FETCH_BREW_MATERIAL_PORTIONS_BY_BREW_ID_SUCCESS =
    "FETCH_BREW_MATERIAL_PORTIONS_BY_BREW_ID_SUCCESS";
export const FETCH_BREW_MATERIAL_PORTIONS_BY_BREW_ID_FAILURE =
    "FETCH_BREW_MATERIAL_PORTIONS_BY_BREW_ID_FAILURE";
export const FETCH_BREW_MATERIAL_PORTIONS_BY_BREW_ID_REQUEST =
    "FETCH_BREW_MATERIAL_PORTIONS_BY_BREW_ID_REQUEST";
export const SET_MATERIAL_PORTIONS = "SET_MATERIAL_PORTIONS";
export const RESET_BREW_MATERIAL_PORTIONS_DETAILS =
    "RESET_BREW_MATERIAL_PORTIONS_DETAILS";
export const ADD_BREW_MATERIAL_PORTIONS_REQUEST =
    "ADD_BREW_MATERIAL_PORTIONS_REQUEST";
export const ADD_BREW_MATERIAL_PORTIONS_SUCCESS =
    "ADD_BREW_MATERIAL_PORTIONS_SUCCESS";
export const ADD_BREW_MATERIAL_PORTIONS_FAILURE =
    "ADD_BREW_MATERIAL_PORTIONS_FAILURE";
export const EDIT_BREW_MATERIAL_PORTIONS_REQUEST =
    "EDIT_BREW_MATERIAL_PORTIONS_REQUEST";
export const EDIT_BREW_MATERIAL_PORTIONS_SUCCESS =
    "EDIT_BREW_MATERIAL_PORTIONS_SUCCESS";
export const EDIT_BREW_MATERIAL_PORTIONS_FAILURE =
    "EDIT_BREW_MATERIAL_PORTIONS_FAILURE";
export const DELETE_BREW_MATERIAL_PORTIONS_REQUEST =
    "DELETE_BREW_MATERIAL_PORTIONS_REQUEST";
export const DELETE_BREW_MATERIAL_PORTIONS_SUCCESS =
    "DELETE_BREW_MATERIAL_PORTIONS_SUCCESS";
export const DELETE_BREW_MATERIAL_PORTIONS_FAILURE =
    "DELETE_BREW_MATERIAL_PORTIONS_FAILURE";
export const SET_BREW_MATERIAL_PORTIONS = "SET_BREW_MATERIAL_PORTIONS";
export const RESET_BREW_MATERIAL_PORTIONS = "RESET_BREW_MATERIAL_PORTIONS";
