export const FETCH_BATCH_MATERIAL_PORTIONS_SUCCESS =
    "FETCH_BATCH_MATERIAL_PORTIONS_SUCCESS";
export const FETCH_BATCH_MATERIAL_PORTIONS_FAILURE =
    "FETCH_BATCH_MATERIAL_PORTIONS_FAILURE";
export const FETCH_BATCH_MATERIAL_PORTIONS_REQUEST =
    "FETCH_BATCH_MATERIAL_PORTIONS_REQUEST";
export const SET_BATCH_MATERIAL_PORTIONS = "SET_BATCH_MATERIAL_PORTIONS";
export const RESET_BATCH_MATERIAL_PORTIONS = "RESET_BATCH_MATERIAL_PORTIONS";
export const EDIT_BATCH_MATERIAL_PORTIONS = "EDIT_BATCH_MATERIAL_PORTIONS";
export const EDIT_BATCH_MATERIAL_PORTIONS_SUCCESS =
    "EDIT_BATCH_MATERIAL_PORTIONS_SUCCESS";
export const EDIT_BATCH_MATERIAL_PORTIONS_FAILURE =
    "EDIT_BATCH_MATERIAL_PORTIONS_FAILURE";
export const UPDATE_BATCH_MATERIAL_PORTIONS_REQUEST =
    "UPDATE_BATCH_MATERIAL_PORTIONS_REQUEST";
export const UPDATE_BATCH_MATERIAL_PORTIONS_SUCCESS =
    "UPDATE_BATCH_MATERIAL_PORTIONS_SUCCESS";
export const UPDATE_BATCH_MATERIAL_PORTIONS_FAILURE =
    "UPDATE_BATCH_MATERIAL_PORTIONS_FAILURE";
export const DELETE_BATCH_MATERIAL_PORTIONS_REQUEST =
    "DELETE_BATCH_MATERIAL_PORTIONS_REQUEST";
export const DELETE_BATCH_MATERIAL_PORTIONS_SUCCESS =
    "DELETE_BATCH_MATERIAL_PORTIONS_SUCCESS";
export const DELETE_BATCH_MATERIAL_PORTIONS_FAILURE =
    "DELETE_BATCH_MATERIAL_PORTIONS_FAILURE";
