export const FETCH_ALL_FINISHED_GOODS_INVENTORY_REQUEST =
    "FETCH_ALL_FINISHED_GOODS_INVENTORY_REQUEST";
export const FETCH_ALL_FINISHED_GOODS_INVENTORY_SUCCESS =
    "FETCH_ALL_FINISHED_GOODS_INVENTORY_SUCCESS";
export const FETCH_FINISHED_GOODS_INVENTORY_REQUEST =
    "FETCH_FINISHED_GOODS_INVENTORY_REQUEST";
export const FETCH_FINISHED_GOODS_INVENTORY_SUCCESS =
    "FETCH_FINISHED_GOODS_INVENTORY_SUCCESS";
export const FETCH_FINISHED_GOODS_INVENTORY_ERROR =
    "FETCH_FINISHED_GOODS_INVENTORY_ERROR";
export const SET_FINISHED_GOODS_INVENTORY_PAGE_INDEX =
    "SET_FINISHED_GOODS_INVENTORY_PAGE_INDEX";
export const SET_FINISHED_GOODS_INVENTORY_PAGE_SIZE =
    "SET_FINISHED_GOODS_INVENTORY_PAGE_SIZE";
