export const FETCH_FINISHED_GOODS_INVENTORY_AGGREGATION_REQUEST =
    "FETCH_FINISHED_GOODS_INVENTORY_AGGREGATION_REQUEST";
export const FETCH_FINISHED_GOODS_INVENTORY_AGGREGATION_SUCCESS =
    "FETCH_FINISHED_GOODS_INVENTORY_AGGREGATION_SUCCESS";
export const FETCH_FINISHED_GOODS_INVENTORY_AGGREGATION_ERROR =
    "FETCH_FINISHED_GOODS_INVENTORY_AGGREGATION_ERROR";
export const FETCH_FINISHED_GOODS_INVENTORY_REQUEST =
    "FETCH_FINISHED_GOODS_INVENTORY_REQUEST";
export const FETCH_FINISHED_GOODS_INVENTORY_SUCCESS =
    "FETCH_FINISHED_GOODS_INVENTORY_SUCCESS";
export const FETCH_FINISHED_GOODS_INVENTORY_ERROR =
    "FETCH_FINISHED_GOODS_INVENTORY_ERROR";
export const SET_FINISHED_GOODS_INVENTORY_AGGREGATION_PAGE_INDEX =
    "SET_FINISHED_GOODS_INVENTORY_AGGREGATION_PAGE_INDEX";
export const SET_FINISHED_GOODS_INVENTORY_AGGREGATION_PAGE_SIZE =
    "SET_FINISHED_GOODS_INVENTORY_AGGREGATION_PAGE_SIZE";
export const SET_FINISHED_GOODS_INVENTORY_PAGE_INDEX =
    "SET_FINISHED_GOODS_INVENTORY_PAGE_INDEX";
export const SET_FINISHED_GOODS_INVENTORY_PAGE_SIZE =
    "SET_FINISHED_GOODS_INVENTORY_PAGE_SIZE";
export const RESET_FINISHED_GOODS_INVENTORY = "RESET_FINISHED_GOODS_INVENTORY";
