export const FETCH_EQUIPMENTS_REQUEST = "FETCH_EQUIPMENTS_REQUEST";
export const FETCH_EQUIPMENTS_SUCCESS = "FETCH_EQUIPMENTS_SUCCESS";
export const FETCH_EQUIPMENTS_FAILURE = "FETCH_EQUIPMENTS_FAILURE";
export const ADD_EQUIPMENTS_REQUEST = "ADD_EQUIPMENTS_REQUEST";
export const ADD_EQUIPMENTS_SUCCESS = "ADD_EQUIPMENTS_SUCCESS";
export const ADD_EQUIPMENTS_FAILURE = "ADD_EQUIPMENTS_FAILURE";
export const EDIT_EQUIPMENTS_REQUEST = "EDIT_EQUIPMENTS_REQUEST";
export const EDIT_EQUIPMENTS_SUCCESS = "EDIT_EQUIPMENTS_SUCCESS";
export const EDIT_EQUIPMENTS_FAILURE = "EDIT_EQUIPMENTS_FAILURE";

