/* Navigation */
export const SET_RAW_MATERIAL_ITEMS = "SET_RAW_MATERIAL_ITEMS";
export const SET_RAW_MATERIAL_DISCOVER = "SET_RAW_MATERIAL_DISCOVER";

/* Active Tabs */
export const SET_RAW_MATERIALS_INVENTORY_VALUE_ACTIVE_TAB = "SET_RAW_MATERIALS_INVENTORY_VALUE_ACTIVE_TAB";