export const FETCH_BATCH_STATUS_REQUEST = "FETCH_BATCH_STATUS_REQUEST";
export const FETCH_BATCH_STATUS_SUCCESS = "FETCH_BATCH_STATUS_SUCCESS";
export const FETCH_BATCH_STATUS_FAILURE = "FETCH_BATCH_STATUS_FAILURE";
export const SET_BATCH_STATUS_DETAILS = "SET_BATCH_STATUS_DETAILS";
export const SET_BATCH_STATUS_PAGE_INDEX = "SET_BATCH_STATUS_PAGE_INDEX";
export const SET_BATCH_STATUS_PAGE_SIZE = "SET_BATCH_STATUS_PAGE_SIZE";
