export const FETCH_CONTACTS_REQUEST = "FETCH_CONTACTS_REQUEST";
export const FETCH_CONTACTS_SUCCESS = "FETCH_CONTACTS_SUCCESS";
export const FETCH_CONTACTS_FAILURE = "FETCH_CONTACTS_FAILURE";

export const FETCH_CONTACT_REQUEST = "FETCH_CONTACT_REQUEST";
export const FETCH_CONTACT_SUCCESS = "FETCH_CONTACT_SUCCESS";
export const FETCH_CONTACT_FAILURE = "FETCH_CONTACT_FAILURE";

export const ADD_CONTACTS_REQUEST = "ADD_CONTACTS_REQUEST";
export const ADD_CONTACTS_SUCCESS = "ADD_CONTACTS_SUCCESS";
export const ADD_CONTACTS_FAILURE = "ADD_CONTACTS_FAILURE";

export const EDIT_CONTACTS_REQUEST = "EDIT_CONTACTS_REQUEST";
export const EDIT_CONTACTS_SUCCESS = "EDIT_CONTACTS_SUCCESS";
export const EDIT_CONTACTS_FAILURE = "EDIT_CONTACTS_FAILURE";

export const DELETE_CONTACTS_REQUEST = "DELETE_CONTACTS_REQUEST";
export const DELETE_CONTACTS_SUCCESS = "DELETE_CONTACTS_SUCCESS";
export const DELETE_CONTACTS_FAILURE = "DELETE_CONTACTS_FAILURE";
