nginx:
  staticSiteConfigmap: html-content
  ingress:
    enabled: true
    tls: true
    pathType: Prefix
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /index.html
      cert-manager.io/cluster-issuer: letsencrypt
      kubernetes.io/ingress.class: "nginx"
  service:
    type: ClusterIP
