export const ADD_SUPPLIER_CONTACT_REQUEST = "ADD_SUPPLIER_CONTACT_REQUEST";
export const ADD_SUPPLIER_CONTACT_SUCCESS = "ADD_SUPPLIER_CONTACT_SUCCESS";
export const ADD_SUPPLIER_CONTACT_FAILURE = "ADD_SUPPLIER_CONTACT_FAILURE";
export const EDIT_SUPPLIER_CONTACT_REQUEST = "  EDIT_SUPPLIER_CONTACT_REQUEST";
export const EDIT_SUPPLIER_CONTACT_SUCCESS = "EDIT_SUPPLIER_CONTACT_SUCCESS";
export const EDIT_SUPPLIER_CONTACT_FAILURE = "EDIT_SUPPLIER_CONTACT_FAILURE";
export const DELETE_SUPPLIER_CONTACT_REQUEST =
    "DELETE_SUPPLIER_CONTACT_REQUEST";
export const DELETE_SUPPLIER_CONTACT_SUCCESS =
    "DELETE_SUPPLIER_CONTACT_SUCCESS";
export const DELETE_SUPPLIER_CONTACT_FAILURE =
    "DELETE_SUPPLIER_CONTACT_FAILURE";
export const FETCH_SUPPLIER_CONTACT_BY_ID_REQUEST =
    "FETCH_SUPPLIER_CONTACT_BY_ID_REQUEST";
export const FETCH_SUPPLIER_CONTACT_BY_ID_SUCCESS =
    "FETCH_SUPPLIER_CONTACT_BY_ID_SUCCESS";
export const FETCH_SUPPLIER_CONTACT_BY_ID_FAILURE =
    "FETCH_SUPPLIER_CONTACT_BY_ID_FAILURE";
export const SET_SUPPLIER_CONTACT_DETAILS = "SET_SUPPLIER_CONTACT_DETAILS";
export const RESET_SUPPLIER_CONTACT_DETAILS = "RESET_SUPPLIER_CONTACT_DETAILS";
export const INVALID_SUPPLIER_CONTACT_FIRST_NAME =
    "INVALID_SUPPLIER_CONTACT_FIRST_NAME";
export const INVALID_SUPPLIER_CONTACT_LAST_NAME =
    "INVALID_SUPPLIER_CONTACT_LAST_NAME";
export const INVALID_SUPPLIER_CONTACT_COMPANY =
    "INVALID_SUPPLIER_CONTACT_COMPANY";
export const INVALID_SUPPLIER_CONTACT_POSITION =
    "INVALID_SUPPLIER_CONTACT_POSITION";
export const INVALID_SUPPLIER_CONTACT_EMAIL = "INVALID_SUPPLIER_CONTACT_EMAIL";
export const INVALID_SUPPLIER_CONTACT_PHONE_NUMBER =
    "INVALID_SUPPLIER_CONTACT_PHONE_NUMBER";
