export const SET_USER_ROLES = "SET_USER_ROLES";
export const SET_USER_ROLES_ERROR = "SET_USER_ROLES_ERROR";
export const SET_ALL_USER_ROLES = "SET_ALL_USER_ROLES";
export const FETCH_USER_ROLES = "FETCH_USER_ROLES";
export const FETCH_ALL_USER_ROLES = "FETCH_ALL_USER_ROLES";
export const SET_USER_ROLES_PAGE_INDEX = "SET_USER_ROLES_PAGE_INDEX";
export const SET_USER_ROLES_PAGE_SIZE = "SET_USER_ROLES_PAGE_SIZE";
