export const ADD_MATERIAL_CATEGORY_REQUEST = "ADD_MATERIAL_CATEGORY_REQUEST";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAILURE = "ADD_CATEGORY_FAILURE";
export const EDIT_MATERIAL_CATEGORY_REQUEST = "EDIT_MATERIAL_CATEGORY_REQUEST";
export const EDIT_MATERIAL_CATEGORY_SUCCESS = "EDIT_MATERIAL_CATEGORY_SUCCESS";
export const EDIT_MATERIAL_CATEGORY_FAILURE = "EDIT_MATERIAL_CATEGORY_FAILURE";
export const DELETE_MATERIAL_CATEGORY_REQUEST =
    "DELETE_MATERIAL_CATEGORY_REQUEST";
export const DELETE_MATERIAL_CATEGORY_SUCCESS =
    "DELETE_MATERIAL_CATEGORY_SUCCESS";
export const DELETE_MATERIAL_CATEGORY_FAILURE =
    "DELETE_MATERIAL_CATEGORY_FAILURE";
export const FETCH_MATERIAL_CATEGORY_BY_ID_REQUEST =
    "FETCH_MATERIAL_CATEGORY_BY_ID_REQUEST";
export const FETCH_MATERIAL_CATEGORY_BY_ID_SUCCESS =
    "FETCH_MATERIAL_CATEGORY_BY_ID_SUCCESS";
export const FETCH_MATERIAL_CATEGORY_BY_ID_FAILURE =
    "FETCH_MATERIAL_CATEGORY_BY_ID_FAILURE";
export const SET_MATERIAL_CATEGORY_DETAILS = "SET_MATERIAL_CATEGORY_DETAILS";
export const RESET_MATERIAL_CATEGORY_DETAILS =
    "RESET_MATERIAL_CATEGORY_DETAILS";
export const INVALID_MATERIAL_CATEGORY_NAME = "INVALID_MATERIAL_CATEGORY_NAME";
export const INVALID_MATERIAL_CATEGORY_PARENT_CATEGORY =
    "INVALID_MATERIAL_CATEGORY_PARENT_CATEGORY";
