export const FETCH_BATCH_FINISHED_GOODS_SUCCESS =
    "FETCH_BATCH_FINISHED_GOODS_SUCCESS";
export const FETCH_BATCH_FINISHED_GOODS_FAILURE =
    "FETCH_BATCH_FINISHED_GOODS_FAILURE";
export const FETCH_BATCH_FINISHED_GOODS_REQUEST =
    "FETCH_BATCH_FINISHED_GOODS_REQUEST";
export const EDIT_BATCH_FINISHED_GOODS = "EDIT_BATCH_FINISHED_GOODS";
export const EDIT_BATCH_FINISHED_GOODS_SUCCESS =
    "EDIT_BATCH_FINISHED_GOODS_SUCCESS";
export const EDIT_BATCH_FINISHED_GOODS_FAILURE =
    "EDIT_BATCH_FINISHED_GOODS_FAILURE";
export const UPDATE_BATCH_FINISHED_GOODS_REQUEST =
    "UPDATE_BATCH_FINISHED_GOODS_REQUEST";
export const UPDATE_BATCH_FINISHED_GOODS_SUCCESS =
    "UPDATE_BATCH_FINISHED_GOODS_SUCCESS";
export const UPDATE_BATCH_FINISHED_GOODS_FAILURE =
    "UPDATE_BATCH_FINISHED_GOODS_FAILURE";
export const DELETE_BATCH_FINISHED_GOODS_REQUEST =
    "DELETE_BATCH_FINISHED_GOODS_REQUEST";
export const DELETE_BATCH_FINISHED_GOODS_SUCCESS =
    "DELETE_BATCH_FINISHED_GOODS_SUCCESS";
export const DELETE_BATCH_FINISHED_GOODS_FAILURE =
    "DELETE_BATCH_FINISHED_GOODS_FAILURE";
export const SET_BATCH_FINISHED_GOODS = "SET_BATCH_FINISHED_GOODS";
export const RESET_BATCH_FINISHED_GOODS = "RESET_BATCH_FINISHED_GOODS";
