export const FETCH_ALL_PURCHASE_INVOICES_REQUEST =
    "FETCH_ALL_PURCHASE_INVOICES_REQUEST";
export const FETCH_ALL_PURCHASE_INVOICES_SUCCESS =
    "FETCH_ALL_PURCHASE_INVOICES_SUCCESS";
export const FETCH_ALL_PURCHASE_INVOICES_FAILURE =
    "FETCH_ALL_PURCHASE_INVOICES_FAILURE";
export const FETCH_PURCHASE_INVOICES_REQUEST =
    "FETCH_PURCHASE_INVOICES_REQUEST";
export const FETCH_PURCHASE_INVOICES_SUCCESS =
    "FETCH_PURCHASE_INVOICES_SUCCESS";
export const FETCH_PURCHASE_INVOICES_FAILURE =
    "FETCH_PURCHASE_INVOICES_FAILURE";
export const SET_PURCHASE_INVOICES_DETAILS = "SET_PURCHASE_INVOICES_DETAILS";
export const SET_PURCHASE_INVOICES_PAGE_INDEX =
    "SET_PURCHASE_INVOICES_PAGE_INDEX";
export const SET_PURCHASE_INVOICES_PAGE_SIZE =
    "SET_PURCHASE_INVOICES_PAGE_SIZE";
export const SET_PURCHASE_INVOICE_ITEM_DETAILS =
    "SET_PURCHASE_INVOICE_ITEM_DETAILS";
