export const FETCH_MEASURE_REQUEST = "FETCH_MEASURE_REQUEST";
export const FETCH_MEASURE_SUCCESS = "FETCH_MEASURE_SUCCESS";
export const FETCH_MEASURE_FAILURE = "FETCH_MEASURE_FAILURE";
export const SET_MEASURE_DETAILS = "SET_MEASURE_DETAILS";
export const SET_MEASURE_PAGE_INDEX = "SET_MEASURE_PAGE_INDEX";
export const SET_MEASURE_PAGE_SIZE = "SET_MEASURE_PAGE_SIZE";
