export const FETCH_MEASURES_REQUEST = "FETCH_MEASURES_REQUEST";
export const FETCH_MEASURES_SUCCESS = "FETCH_MEASURES_SUCCESS";
export const FETCH_MEASURES_FAILURE = "FETCH_MEASURES_FAILURE";
export const SET_MEASURE_DETAILS = "SET_MEASURE_DETAILS";
export const SET_MEASURE_PAGE_INDEX = "SET_MEASURE_PAGE_INDEX";
export const SET_MEASURE_PAGE_SIZE = "SET_MEASURE_PAGE_SIZE";
