export const FETCH_MEASURES = "FETCH_MEASURES";
export const SET_MEASURES = "SET_MEASURES";
export const SET_MEASURE_DETAILS = "SET_MEASURE_DETAILS";
export const SET_MEASURE_PAGE_INDEX = "SET_MEASURE_PAGE_INDEX";
export const SET_MEASURE_PAGE_SIZE = "SET_MEASURE_PAGE_SIZE";
