export const FETCH_FACILITIES_REQUEST = "FETCH_FACILITIES_REQUEST";
export const FETCH_FACILITIES_SUCCESS = "FETCH_FACILITIES_SUCCESS";
export const FETCH_FACILITIES_FAILURE = "FETCH_FACILITIES_FAILURE";

export const FETCH_FACILITY_REQUEST = "FETCH_FACILITY_REQUEST";
export const FETCH_FACILITIY_SUCCESS = "FETCH_FACILITY_SUCCESS";
export const FETCH_FACILITY_FAILURE = "FETCH_FACILITY_FAILURE";

export const CREATE_FACILITY_REQUEST = "CREATE_FACILITY_REQUEST";
export const CREATE_FACILITIY_SUCCESS = "CREATE_FACILITY_SUCCESS";
export const CREATE_FACILITY_FAILURE = "CREATE_FACILITY_FAILURE";

export const UPDATE_FACILITY_REQUEST = "UPDATE_FACILITY_REQUEST";
export const UPDATE_FACILITIY_SUCCESS = "UPDATE_FACILITY_SUCCESS";
export const UPDATE_FACILITY_FAILURE = "UPDATE_FACILITY_FAILURE";

export const DELETE_FACILITY_REQUEST = "DELETE_FACILITY_REQUEST";
export const DELETE_FACILITIY_SUCCESS = "DELETE_FACILITY_SUCCESS";
export const DELETE_FACILITY_FAILURE = "DELETE_FACILITY_FAILURE";
