export const SET_BATCHES = "SET_BATCHES";
export const SET_BATCHES_PAGE_INDEX = "SET_BATCHES_PAGE_INDEX";
export const SET_BATCHES_PAGE_SIZE = "SET_BATCHES_PAGE_SIZE";
export const SET_BATCHES_CLASS = "SET_BATCHES_CLASS";
export const SET_BATCHES_TYPE = "SET_BATCHES_TYPE";
export const SET_BATCHES_SIZE = "SET_BATCHES_SIZE";