export const SET_DATA = 'SET_DATA';
export const GET_SUPPLIERS_DATA = 'GET_SUPPLIERS_DATA';
export const CREATE_SUPPLIER = 'CREATE_SUPPLIER';
export const DELETE_SUPPLIER = 'DELETE_SUPPLIER';
export const UPDATE_SUPPLIER = 'UPDATE_SUPPLIER';
