export const FETCH_STORAGES_REQUEST = "FETCH_STORAGES_REQUEST";
export const FETCH_STORAGES_SUCCESS = "FETCH_STORAGES_SUCCESS";
export const FETCH_STORAGES_FAILURE = "FETCH_STORAGES_FAILURE";

export const CREATE_STORAGES_REQUEST = "CREATE_STORAGES_REQUEST";
export const CREATE_STORAGES_SUCCESS = "CREATE_STORAGES_SUCCESS";
export const CREATE_STORAGES_FAILURE = "CREATE_STORAGES_FAILURE";

export const UPDATE_STORAGES_REQUEST = "UPDATE_STORAGES_REQUEST";
export const UPDATE_STORAGES_SUCCESS = "UPDATE_STORAGES_SUCCESS";
export const UPDATE_STORAGES_FAILURE = "UPDATE_STORAGES_FAILURE";

export const DELETE_STORAGES_REQUEST = "DELETE_STORAGES_REQUEST";
export const DELETE_STORAGES_SUCCESS = "DELETE_STORAGES_SUCCESS";
export const DELETE_STORAGES_FAILURE = "DELETE_STORAGES_FAILURE";
