export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_ALL_PRODUCTS = "FETCH_ALL_PRODUCTS";
export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_PRODUCTS_PAGE_INDEX = "SET_PRODUCTS_PAGE_INDEX";
export const SET_PRODUCTS_PAGE_SIZE = "SET_PRODUCTS_PAGE_SIZE";
export const SET_PRODUCTS_CLASS = "SET_PRODUCTS_CLASS";
export const SET_PRODUCTS_TYPE = "SET_PRODUCTS_TYPE";
export const SET_PRODUCTS_STYLE = "SET_PRODUCTS_STYLE";