export const FETCH_ALL_BREW_STAGE_REQUEST = "FETCH_ALL_BREW_STAGE_REQUEST";
export const FETCH_ALL_BREW_STAGE_SUCCESS = "FETCH_ALL_BREW_STAGE_SUCCESS";
export const FETCH_ALL_BREW_STAGE_FAILURE = "FETCH_ALL_BREW_STAGE_FAILURE";
export const FETCH_BREW_STAGE_BY_BREW_ID_REQUEST =
    "FETCH_BREW_STAGE_BY_BREW_ID_REQUEST";
export const FETCH_BREW_STAGES_BY_BREW_ID_SUCCESS =
    "FETCH_BREW_STAGES_BY_BREW_ID_SUCCESS";
export const FETCH_BREW_STAGES_BY_BREW_ID_FAILURE =
    "FETCH_BREW_STAGES_BY_BREW_ID_FAILURE";
export const ADD_BREW_STAGE_REQUEST = "ADD_BREW_STAGE_REQUEST";
export const ADD_BREW_STAGE_SUCCESS = "ADD_BREW_STAGE_SUCCESS";
export const ADD_BREW_STAGE_FAILURE = "ADD_BREW_STAGE_FAILURE";
export const EDIT_BREW_STAGES_REQUEST = "EDIT_BREW_STAGES_REQUEST";
export const EDIT_BREW_STAGES_SUCCESS = "EDIT_BREW_STAGES_SUCCESS";
export const EDIT_BREW_STAGES_FAILURE = "EDIT_BREW_STAGES_FAILURE";
export const DELETE_BREW_STAGE_REQUEST = "DELETE_BREW_STAGE_REQUEST";
export const DELETE_BREW_STAGE_SUCCESS = "DELETE_BREW_STAGE_SUCCESS";
export const DELETE_BREW_STAGE_FAILURE = "DELETE_BREW_STAGE_FAILURE";
export const SET_BREW_STAGES = "SET_BREW_STAGES";
export const RESET_BREW_STAGES = "RESET_BREW_STAGES";

export const SET_MASH_STAGE_DETAILS = "SET_MASH_STAGE_DETAILS";
export const RESET_MASH_STAGE_DETAILS = "RESET_MASH_STAGE_DETAILS";

export const SET_KETTLE_STAGE_DETAILS = "SET_KETTLE_STAGE_DETAILS";
export const RESET_KETTLE_STAGE_DETAILS = "RESET_KETTLE_STAGE_DETAILS";

export const SET_WHIRLPOOL_STAGE_DETAILS = "SET_WHIRLPOOL_STAGE_DETAILS";
export const RESET_WHIRLPOOL_STAGE_DETAILS = "RESET_WHIRLPOOL_STAGE_DETAILS";

export const SET_TRANSFER_STAGE_DETAILS = "SET_TRANSFER_STAGE_DETAILS";
export const RESET_TRANSFER_STAGE_DETAILS = "RESET_TRANSFER_STAGE_DETAILS";

export const FETCH_FERMENT_STAGE_BY_ID_REQUEST =
    "FETCH_FERMENT_STAGE_BY_ID_REQUEST";
export const ADD_FERMENT_STAGE_REQUEST = "ADD_FERMENT_STAGE_REQUEST";
export const ADD_FERMENT_STAGE_SUCCESS = "ADD_FERMENT_STAGE_SUCCESS";
export const ADD_FERMENT_STAGE_FAILURE = "ADD_FERMENT_STAGE_FAILURE";
export const EDIT_FERMENT_STAGE_REQUEST = "EDIT_FERMENT_STAGE_REQUEST";
export const EDIT_FERMENT_STAGE_SUCCESS = "EDIT_FERMENT_STAGE_SUCCESS";
export const EDIT_FERMENT_STAGE_FAILURE = "EDIT_FERMENT_STAGE_FAILURE";
export const DELETE_FERMENT_STAGE_REQUEST = "DELETE_FERMENT_STAGE_REQUEST";
export const DELETE_FERMENT_STAGE_SUCCESS = "DELETE_FERMENT_STAGE_SUCCESS";
export const DELETE_FERMENT_STAGE_FAILURE = "DELETE_FERMENT_STAGE_FAILURE";
export const SET_FERMENT_STAGE_DETAILS = "SET_FERMENT_STAGE_DETAILS";
export const RESET_FERMENT_STAGE_DETAILS = "RESET_FERMENT_STAGE_DETAILS";
export const SET_FERMENT_STAGE_INVALID_NAME = "SET_FERMENT_STAGE_INVALID_NAME";
export const SET_FERMENT_STAGE_INVALID_CATEGORY =
    "SET_FERMENT_STAGE_INVALID_CATEGORY";

export const FETCH_CONDITION_STAGE_BY_ID_REQUEST =
    "FETCH_CONDITION_STAGE_BY_ID_REQUEST";
export const ADD_CONDITION_STAGE_REQUEST = "ADD_CONDITION_STAGE_REQUEST";
export const ADD_CONDITION_STAGE_SUCCESS = "ADD_CONDITION_STAGE_SUCCESS";
export const ADD_CONDITION_STAGE_FAILURE = "ADD_CONDITION_STAGE_FAILURE";
export const EDIT_CONDITION_STAGE_REQUEST = "EDIT_CONDITION_STAGE_REQUEST";
export const EDIT_CONDITION_STAGE_SUCCESS = "EDIT_CONDITION_STAGE_SUCCESS";
export const EDIT_CONDITION_STAGE_FAILURE = "EDIT_CONDITION_STAGE_FAILURE";
export const DELETE_CONDITION_STAGE_REQUEST = "DELETE_CONDITION_STAGE_REQUEST";
export const DELETE_CONDITION_STAGE_SUCCESS = "DELETE_CONDITION_STAGE_SUCCESS";
export const DELETE_CONDITION_STAGE_FAILURE = "DELETE_CONDITION_STAGE_FAILURE";
export const SET_CONDITION_STAGE_DETAILS = "SET_CONDITION_STAGE_DETAILS";
export const RESET_CONDITION_STAGE_DETAILS = "RESET_CONDITION_STAGE_DETAILS";
export const SET_CONDITION_STAGE_INVALID_NAME =
    "SET_CONDITION_STAGE_INVALID_NAME";
export const SET_CONDITION_STAGE_INVALID_CATEGORY =
    "SET_CONDITION_STAGE_INVALID_CATEGORY";

export const FETCH_BRITE_TANK_STAGE_BY_ID_REQUEST =
    "FETCH_BRITE_TANK_STAGE_BY_ID_REQUEST";
export const ADD_BRITE_TANK_STAGE_REQUEST = "ADD_BRITE_TANK_STAGE_REQUEST";
export const ADD_BRITE_TANK_STAGE_SUCCESS = "ADD_BRITE_TANK_STAGE_SUCCESS";
export const ADD_BRITE_TANK_STAGE_FAILURE = "ADD_BRITE_TANK_STAGE_FAILURE";
export const EDIT_BRITE_TANK_STAGE_REQUEST = "EDIT_BRITE_TANK_STAGE_REQUEST";
export const EDIT_BRITE_TANK_STAGE_SUCCESS = "EDIT_BRITE_TANK_STAGE_SUCCESS";
export const EDIT_BRITE_TANK_STAGE_FAILURE = "EDIT_BRITE_TANK_STAGE_FAILURE";
export const DELETE_BRITE_TANK_STAGE_REQUEST =
    "DELETE_BRITE_TANK_STAGE_REQUEST";
export const DELETE_BRITE_TANK_STAGE_SUCCESS =
    "DELETE_BRITE_TANK_STAGE_SUCCESS";
export const DELETE_BRITE_TANK_STAGE_FAILURE =
    "DELETE_BRITE_TANK_STAGE_FAILURE";
export const SET_BRITE_TANK_STAGE_DETAILS = "SET_BRITE_TANK_STAGE_DETAILS";
export const RESET_BRITE_TANK_STAGE_DETAILS = "RESET_BRITE_TANK_STAGE_DETAILS";
export const SET_BRITE_TANK_STAGE_INVALID_NAME =
    "SET_BRITE_TANK_STAGE_INVALID_NAME";
export const SET_BRITE_TANK_STAGE_INVALID_CATEGORY =
    "SET_BRITE_TANK_STAGE_INVALID_CATEGORY";
