export const SET_FINISHED_GOOD_DETAILS = "SET_FINISHED_GOOD_DETAILS";
export const SET_FINISHED_GOOD_DETAILS_ERROR =
    "SET_FINISHED_GOOD_DETAILS_ERROR";
export const FETCH_FINISHED_GOOD = "FETCH_FINISHED_GOOD";
export const CREATE_FINISHED_GOOD = "CREATE_FINISHED_GOOD";
export const UPDATE_FINISHED_GOOD = "UPDATE_FINISHED_GOOD";
export const DELETE_FINISHED_GOOD = "DELETE_FINISHED_GOOD";
export const INVALID_SKU = "INVALID_SKU";
export const INVALID_MATERIAL_PORTIONS = "INVALID_MATERIAL_PORTIONS";
export const INVALID_MIXTURE_PORTIONS = "INVALID_MIXTURE_PORTIONS";
export const INVALID_FINISHED_GOOD_LOT_PORTIONS =
    "INVALID_FINISHED_GOOD_LOT_PORTIONS";
export const INVALID_PACKAGED_ON = "INVALID_PACKAGED_ON";
export const INVALID_QUANTITY = "INVALID_QUANTITY";
export const RESET_FINISHED_GOOD_DETAILS = "RESET_FINISHED_GOOD_DETAILS";
