# https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
jobs:
    build:
        runs-on: ubuntu-latest
        env:
            SKIP_PREFLIGHT_CHECK: true
        strategy:
            matrix:
                # node-version: [12.x, 14.x, 16.x]
                node-version: [12.x, 14.x]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  # cache: "npm"
                  # cache-dependency-path: package-lock.json
            - run: npm install
            - run: npm run build
            - run: npm run eslint
            - run: npm run prettier:warn
            - run: npm run test
